const fs=require('fs'),path=require('path');
const CUTS=[10,12,14,16],RETS=[.70,.80,.85,.90,.95],CAPS=[30,40,50,100];
const pair=(a,b)=>{a=+a;b=+b;return a<b?a+'-'+b:b+'-'+a};
function combos(r){const [fa,fb]=r.framePair.split('-').map(Number),A=r.horses.filter(x=>x.frame===fa),B=r.horses.filter(x=>x.frame===fb),o=[];if(fa===fb){for(let i=0;i<A.length;i++)for(let j=i+1;j<A.length;j++)o.push({key:pair(A[i].horse,A[j].horse),raw:A[i].w*A[j].w,a:A[i],b:A[j]})}else for(const a of A)for(const b of B)o.push({key:pair(a.horse,b.horse),raw:a.w*b.w,a,b});const tot=o.reduce((s,x)=>s+x.raw,0);o.forEach(x=>x.p=tot?x.raw/tot:0);o.sort((a,b)=>b.p-a.p);return o}
function retained(r,ret){const o=combos(r),out=[];let s=0;for(const x of o){out.push(x);s+=x.p;if(s+1e-12>=ret)break}return out}
function zone(k){if(k===1||(k>=13&&k<=18))return'A';if(k===2||k===3||(k>=10&&k<=12))return'B';if(k>=4&&k<=9)return'C';return'D'}
function wilson(h,n,z=1.96){if(!n)return null;const p=h/n,z2=z*z,d=1+z2/n,c=(p+z2/(2*n))/d,m=z*Math.sqrt((p*(1-p)+z2/(4*n))/n)/d;return{low:Math.max(0,c-m),high:Math.min(1,c+m)}}
function pct(x){return x==null?'—':(100*x).toFixed(1)+'%'}
function stat(rows,cut,ret){let fh=0,ch=0,pts=0;for(const r of rows){const f=r.frameRank>=3&&r.frameRank<=cut;if(f)fh++;const k=retained(r,ret);if(f)pts+=k.length;if(f&&k.some(x=>x.key===pair(r.first.horse,r.second.horse)))ch++}return{n:rows.length,cut,ret,frameHits:fh,frameRate:fh/rows.length,convertedHits:ch,convertedRate:ch/rows.length,conversionGivenFrame:fh?ch/fh:null,avgPointsWhenFrameTargeted:fh?pts/fh:null,frameCI:wilson(fh,rows.length),convertedCI:wilson(ch,rows.length)}}
function capStat(rows,cut,cap){let fh=0,h=0,pts=0;for(const r of rows){if(!(r.frameRank>=3&&r.frameRank<=cut))continue;fh++;const k=combos(r).filter(x=>x.a.odds<cap&&x.b.odds<cap);pts+=k.length;if(k.some(x=>x.key===pair(r.first.horse,r.second.horse)))h++}return{n:rows.length,cut,cap,frameHits:fh,hit:h,conversionGivenFrame:fh?h/fh:null,avgPoints:fh?pts/fh:null}}
function zones(rows){const z={A:0,B:0,C:0,D:0};rows.forEach(r=>z[zone(r.frameRank)]++);return Object.fromEntries(Object.entries(z).map(([k,n])=>[k,{n,rate:n/rows.length}]))}
function marginal(rows,a,b,ret){let addFrame=0,addConv=0,extraPts=0;for(const r of rows){const A=r.frameRank>=3&&r.frameRank<=a,B=r.frameRank>=3&&r.frameRank<=b;if(B&&!A){addFrame++;const k=retained(r,ret);extraPts+=k.length;if(k.some(x=>x.key===pair(r.first.horse,r.second.horse)))addConv++}}return{from:a,to:b,ret,n:rows.length,addFrame,addConv,extraPts,pointsPerAddedConverted:addConv?extraPts/addConv:null}}
function winningPairMass(rows){const ts=[.5,.6,.7,.8,.85,.9,.95,1],out=Object.fromEntries(ts.map(t=>[t,0]));let rank=0;for(const r of rows){const cs=combos(r),act=pair(r.first.horse,r.second.horse);let cum=0,found=1;for(let i=0;i<cs.length;i++){cum+=cs[i].p;if(cs[i].key===act){found=cum;rank+=i+1;break}}for(const t of ts)if(found<=t+1e-12)out[t]++}return{n:rows.length,avgActualPairRank:rank/rows.length,capture:Object.fromEntries(ts.map(t=>[t,{n:out[t],rate:out[t]/rows.length}]))}}
function mdTable(a,cols){let s='|'+cols.map(c=>c.h).join('|')+'|\\n|'+cols.map(()=> '---').join('|')+'|\\n';for(const x of a)s+='|'+cols.map(c=>c.f(x)).join('|')+'|\\n';return s}
const dir='analysis/waku-backtest/year-merge',files=fs.readdirSync(dir).filter(f=>/^races-\d\d\.json$/.test(f)),rows=files.flatMap(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'))).sort((a,b)=>a.id.localeCompare(b.id));
const failures=fs.readdirSync(dir).filter(f=>/^failures-\d\d\.json$/.test(f)).flatMap(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8')));
const dev=rows.filter(r=>r.year<=2023),test=rows.filter(r=>r.year>=2024),grid=[];for(const c of CUTS)for(const r of RETS)grid.push({dev:stat(dev,c,r),test:stat(test,c,r),all:stat(rows,c,r)});
const report={requested:393,usable:rows.length,failures,devN:dev.length,testN:test.length,zonesAll:zones(rows),zonesDev:zones(dev),zonesTest:zones(test),grid,marginal12to14:RETS.map(r=>({dev:marginal(dev,12,14,r),test:marginal(test,12,14,r)})),caps14:CAPS.map(c=>({dev:capStat(dev,14,c),test:capStat(test,14,c)})),winningPairMassDev:winningPairMass(dev),winningPairMassTest:winningPairMass(test)};
fs.mkdirSync('analysis/waku-backtest/combined-out',{recursive:true});fs.writeFileSync('analysis/waku-backtest/combined-out/report.json',JSON.stringify(report,null,2));
let md='# 枠連BC思想・2022–2025 過去検証\\n\\n利用可能 '+rows.length+'/393R。2022–23 '+dev.length+'R（条件設定側） / 2024–25 '+test.length+'R（ホールドアウト側）。確定オッズ使用。\\n\\n## 実際の枠連決着区画\\n\\n';
md+=mdTable(['A','B','C','D'].map(k=>({k,a:report.zonesAll[k],d:report.zonesDev[k],t:report.zonesTest[k]})),[{h:'区画',f:x=>x.k},{h:'全体',f:x=>x.a.n+'/'+rows.length+' ('+pct(x.a.rate)+')'},{h:'2022-23',f:x=>x.d.n+'/'+dev.length+' ('+pct(x.d.rate)+')'},{h:'2024-25',f:x=>x.t.n+'/'+test.length+' ('+pct(x.t.rate)+')'}]);
md+='\\n## 枠連3〜K捕捉 → 正解枠内を単勝支持で削った場合（2024–25）\\n\\n';
md+=mdTable(grid.map(x=>x.test),[{h:'枠連帯',f:x=>'3〜'+x.cut},{h:'保持率',f:x=>Math.round(x.ret*100)+'%'},{h:'枠捕捉',f:x=>pct(x.frameRate)},{h:'最終捕捉',f:x=>pct(x.convertedRate)},{h:'枠的中時の馬変換成功',f:x=>pct(x.conversionGivenFrame)},{h:'正解枠内平均点',f:x=>x.avgPointsWhenFrameTargeted?.toFixed(2)||'—'}]);
md+='\\n## 12→14位を追加する限界効率（2024–25）\\n\\n'+mdTable(report.marginal12to14.map(x=>x.test),[{h:'保持率',f:x=>Math.round(x.ret*100)+'%'},{h:'追加枠捕捉',f:x=>x.addFrame},{h:'追加最終捕捉',f:x=>x.addConv},{h:'追加正解枠内点数',f:x=>x.extraPts},{h:'1追加捕捉あたり点数',f:x=>x.pointsPerAddedConverted?.toFixed(2)||'—'}]);
md+='\\n## 3〜14位・固定単勝上限（2024–25）\\n\\n'+mdTable(report.caps14.map(x=>x.test),[{h:'単勝上限',f:x=>'<'+x.cap+'倍'},{h:'枠的中時変換成功',f:x=>pct(x.conversionGivenFrame)},{h:'正解枠内平均点',f:x=>x.avgPoints?.toFixed(2)||'—'}]);
md+='\\n## 正解枠内の実馬連支持位置（2024–25）\\n\\n平均順位 '+report.winningPairMassTest.avgActualPairRank.toFixed(2)+'位。\\n\\n'+mdTable(Object.entries(report.winningPairMassTest.capture).map(([t,v])=>({t:+t,v})),[{h:'枠内累積支持まで残す',f:x=>Math.round(x.t*100)+'%'},{h:'実馬連捕捉',f:x=>pct(x.v.rate)}]);
md+='\\n取得失敗 '+failures.length+'R。\\n';fs.writeFileSync('analysis/waku-backtest/combined-out/report.md',md);console.log(md);