const fs=require('fs'),path=require('path');
const CUTS=[10,12,14,16],RETS=[.70,.80,.85,.90,.95],CAPS=[30,40,50,100],dir='analysis/waku-backtest/full-merge';
const pair=(a,b)=>{a=+a;b=+b;return a<b?a+'-'+b:b+'-'+a};
function combos(h,fp){const [fa,fb]=fp.split('-').map(Number),A=h.filter(x=>x.frame===fa),B=h.filter(x=>x.frame===fb),o=[];if(fa===fb){for(let i=0;i<A.length;i++)for(let j=i+1;j<A.length;j++)o.push({key:pair(A[i].horse,A[j].horse),a:A[i],b:A[j],raw:A[i].w*A[j].w})}else for(const a of A)for(const b of B)o.push({key:pair(a.horse,b.horse),a,b,raw:a.w*b.w});const tot=o.reduce((s,x)=>s+x.raw,0);o.forEach(x=>x.p=tot?x.raw/tot:0);o.sort((a,b)=>b.p-a.p);return o}
function keep(o,t){let s=0,a=[];for(const x of o){a.push(x);s+=x.p;if(s+1e-12>=t)break}return a}
function evalOne(r,cut,ret){const m=new Map;for(const f of r.frames.filter(x=>x.rank>=3&&x.rank<=cut))for(const x of keep(combos(r.horses,f.pair),ret))m.set(x.key,x);const actual=pair(r.first.horse,r.second.horse),hit=m.has(actual),fh=r.actualFrameRank>=3&&r.actualFrameRank<=cut,ur=new Map(r.ur),q=ur.get(actual),pts=m.size;return{fh,hit,pts,stake:pts*100,pay:hit&&q?q.odds*100:0}}
function evalCap(r,cut,cap){const s=new Set;for(const f of r.frames.filter(x=>x.rank>=3&&x.rank<=cut))for(const x of combos(r.horses,f.pair))if(x.a.win<cap&&x.b.win<cap)s.add(x.key);const act=pair(r.first.horse,r.second.horse),hit=s.has(act),q=new Map(r.ur).get(act);return{fh:r.actualFrameRank>=3&&r.actualFrameRank<=cut,hit,pts:s.size,stake:s.size*100,pay:hit&&q?q.odds*100:0}}
function sum(rows,cut,ret){const x=rows.map(r=>evalOne(r,cut,ret)),n=x.length,fh=x.filter(z=>z.fh).length,h=x.filter(z=>z.hit).length,pts=x.reduce((s,z)=>s+z.pts,0),st=x.reduce((s,z)=>s+z.stake,0),pay=x.reduce((s,z)=>s+z.pay,0);return{n,cut,ret,frameHits:fh,frameRate:fh/n,hits:h,hitRate:h/n,conversionGivenFrame:fh?h/fh:null,avgPoints:pts/n,pointEfficiency:pts?h/pts:null,stake:st,payout:pay,roi:st?pay/st:null}}
function capsum(rows,cut,cap){const x=rows.map(r=>evalCap(r,cut,cap)),n=x.length,fh=x.filter(z=>z.fh).length,h=x.filter(z=>z.hit).length,pts=x.reduce((s,z)=>s+z.pts,0),st=x.reduce((s,z)=>s+z.stake,0),pay=x.reduce((s,z)=>s+z.pay,0);return{n,cut,cap,frameRate:fh/n,hitRate:h/n,conversionGivenFrame:fh?h/fh:null,avgPoints:pts/n,roi:st?pay/st:null}}
function pct(x){return x==null?'—':(100*x).toFixed(1)+'%'}function table(a,c){let s='|'+c.map(x=>x.h).join('|')+'|\\n|'+c.map(()=> '---').join('|')+'|\\n';for(const x of a)s+='|'+c.map(z=>z.f(x)).join('|')+'|\\n';return s}
const races=fs.readdirSync(dir).filter(f=>/^races-\d\d-\d\.json$/.test(f)).flatMap(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'))).sort((a,b)=>a.id.localeCompare(b.id)),fails=fs.readdirSync(dir).filter(f=>/^fail-\d\d-\d\.json$/.test(f)).flatMap(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'))),dev=races.filter(r=>r.year<=2023),test=races.filter(r=>r.year>=2024),grid=[];for(const c of CUTS)for(const t of RETS)grid.push({dev:sum(dev,c,t),test:sum(test,c,t),all:sum(races,c,t)});const caps=[];for(const c of CAPS)caps.push({dev:capsum(dev,14,c),test:capsum(test,14,c)});
const best=[...grid].sort((a,b)=>b.dev.roi-a.dev.roi)[0],report={usable:races.length,failures:fails,devN:dev.length,testN:test.length,grid,caps,bestDev:{cut:best.dev.cut,ret:best.dev.ret,dev:best.dev,test:best.test}};fs.mkdirSync('analysis/waku-backtest/full-combined',{recursive:true});fs.writeFileSync('analysis/waku-backtest/full-combined/report.json',JSON.stringify(report,null,2));
let md='# 枠連BC・完全馬券バックテスト\\n\\n'+races.length+'/393R取得。2022–23 '+dev.length+'Rで設定、2024–25 '+test.length+'Rをホールドアウト。全枠連オッズ＋全馬連オッズ＋確定単勝を使用。\\n\\n';
md+=table(grid.map(x=>({d:x.dev,t:x.test})),[{h:'枠連帯',f:x=>'3〜'+x.t.cut},{h:'保持',f:x=>Math.round(x.t.ret*100)+'%'},{h:'開発ROI',f:x=>pct(x.d.roi)},{h:'検証ROI',f:x=>pct(x.t.roi)},{h:'検証的中率',f:x=>pct(x.t.hitRate)},{h:'検証平均点',f:x=>x.t.avgPoints.toFixed(2)},{h:'検証枠捕捉',f:x=>pct(x.t.frameRate)},{h:'変換成功/枠的中',f:x=>pct(x.t.conversionGivenFrame)}]);
md+='\\n## 開発期間ROI最大設定を固定して検証\\n\\n2022–23で選択：**3〜'+best.dev.cut+'位 × '+Math.round(best.dev.ret*100)+'%保持**。開発ROI '+pct(best.dev.roi)+'。\\n\\n2024–25：ROI **'+pct(best.test.roi)+'**、的中率 '+pct(best.test.hitRate)+'、平均 '+best.test.avgPoints.toFixed(2)+'点、枠捕捉 '+pct(best.test.frameRate)+'、枠的中時変換 '+pct(best.test.conversionGivenFrame)+'。\\n\\n';
md+='## 3〜14位・単勝固定カット\\n\\n'+table(caps.map(x=>({d:x.dev,t:x.test})),[{h:'上限',f:x=>'<'+x.t.cap+'倍'},{h:'開発ROI',f:x=>pct(x.d.roi)},{h:'検証ROI',f:x=>pct(x.t.roi)},{h:'検証的中率',f:x=>pct(x.t.hitRate)},{h:'検証平均点',f:x=>x.t.avgPoints.toFixed(2)},{h:'変換成功/枠的中',f:x=>pct(x.t.conversionGivenFrame)}]);md+='\\n取得失敗 '+fails.length+'R。\\n';fs.writeFileSync('analysis/waku-backtest/full-combined/report.md',md);console.log(md);