const fs=require('fs');const cheerio=require('cheerio');
const yy='26',chunk=Number(process.env.CHUNK||0),chunks=4;
if(!Number.isInteger(chunk)||chunk<0||chunk>=chunks)throw Error('CHUNK');
const discovered=JSON.parse(fs.readFileSync('analysis/waku-backtest/external-ids/discovered-2026.json','utf8'));
const all=discovered.map(x=>String(x.id));
const ids=all.filter((_,i)=>i%chunks===chunk),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const pair=(a,b)=>{a=+a;b=+b;return a<b?a+'-'+b:b+'-'+a};
function num(s){const x=Number(String(s).replace(/,/g,'').replace(/倍/g,''));return Number.isFinite(x)?x:null}
async function get(url){let last;for(let k=0;k<4;k++){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 historical-racing-research','accept-language':'ja,en-US;q=.7'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('HTTP '+r.status);const t=await r.text();if(t.length<1000)throw Error('short');return t}catch(e){last=e;await sleep([500,1200,2500,4500][k])}}throw last}
function cells($,tr){return $(tr).find('th,td').map((_,x)=>$(x).text().replace(/\s+/g,' ').trim()).get()}
function parseTfw(html){const $=cheerio.load(html),horses=[],frames=[];$('tr').each((_,tr)=>{const c=cells($,tr);if(c.length>=5&&/^\d+$/.test(c[0]||'')&&/^\d+$/.test(c[1]||'')&&/^\d+$/.test(c[2]||'')&&+c[1]<=8&&+c[2]<=18){const o=num(c[4]);if(o&&o<1000)horses.push({pop:+c[0],frame:+c[1],horse:+c[2],name:c[3],win:o,w:1/o})}if(c.length>=3&&/^\d+$/.test(c[0]||'')&&/^[1-8]\s*-\s*[1-8]$/.test(c[1]||'')){const o=num(c[2]);if(o)frames.push({rank:+c[0],pair:c[1].replace(/\s/g,''),odds:o})}});const hu=[...new Map(horses.map(x=>[x.horse,x])).values()].sort((a,b)=>a.horse-b.horse),fu=[...new Map(frames.map(x=>[x.rank,x])).values()].sort((a,b)=>a.rank-b.rank);if(hu.length<5||fu.length<10)throw Error('tfw '+hu.length+'/'+fu.length);return{horses:hu,frames:fu}}
function parseResult(html){const $=cheerio.load(html),rows=[];$('tr').each((_,tr)=>{const c=cells($,tr);if((c[0]==='1'||c[0]==='2')&&/^\d+$/.test(c[1]||'')&&/^\d+$/.test(c[2]||'')&&+c[1]<=8&&+c[2]<=18)rows.push({finish:+c[0],frame:+c[1],horse:+c[2]})});const first=rows.find(x=>x.finish===1),second=rows.find(x=>x.finish===2);if(!first||!second)throw Error('result');return{first,second}}
function parseUr(html){const $=cheerio.load(html),out=[];$('tr').each((_,tr)=>{const c=cells($,tr);if(/^\d+$/.test(c[0]||'')&&/^\d{1,2}\s*-\s*\d{1,2}$/.test(c[1]||'')){const o=num(c[2]);if(o)out.push([c[1].replace(/\s/g,''),{rank:+c[0],odds:o}])}});if(out.length<10)throw Error('ur '+out.length);return out}
async function one(id,i){try{const b='https://sports.yahoo.co.jp/keiba/race/';const [t,r,u]=await Promise.all([get(b+'odds/tfw/'+id+'?ninki=1'),get(b+'result/'+id+'/'),get(b+'odds/ur/'+id+'?ninki=1')]);const a=parseTfw(t),z=parseResult(r),ur=parseUr(u),actual=pair(z.first.frame,z.second.frame),fm=a.frames.find(x=>x.pair===actual);if(!fm)throw Error('frame rank');if(!new Map(ur).get(pair(z.first.horse,z.second.horse)))throw Error('q actual');if((i+1)%10===0)console.log(yy,chunk,'fetched',i+1,'/',ids.length);return{id,year:2000+ +id.slice(0,2),raceNo:+id.slice(-2),horses:a.horses,frames:a.frames,ur,first:z.first,second:z.second,actualFrame:actual,actualFrameRank:fm.rank}}catch(e){console.error('FAIL',id,e.message);return{id,error:e.message}}}
(async()=>{const out=[];for(let i=0;i<ids.length;i++){out.push(await one(ids[i],i));await sleep(60)}const good=out.filter(x=>!x.error),bad=out.filter(x=>x.error);fs.mkdirSync('analysis/waku-backtest/full-chunk-out',{recursive:true});fs.writeFileSync('analysis/waku-backtest/full-chunk-out/races-'+yy+'-'+chunk+'.json',JSON.stringify(good));fs.writeFileSync('analysis/waku-backtest/full-chunk-out/fail-'+yy+'-'+chunk+'.json',JSON.stringify(bad));console.log('CHUNK',yy,chunk,'usable',good.length,'/',ids.length,'fail',bad.length)})().catch(e=>{console.error(e);process.exit(1)});