(()=>{'use strict';
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),P=x=>Number.isFinite(x)?Math.round(x*100)+'%':'—';
let open=false,busy=false,renderTimer=0,lastSig='';
const st=document.createElement('style');st.textContent=`
#scenarioView{display:grid;gap:10px;margin-top:10px}.sv{background:#081a27;border:1px solid #24475b;border-radius:15px;padding:12px}.sv h2{font-size:17px;margin:0 0 8px}.sv h3{font-size:13px;margin:11px 0 6px}.g3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.bx,.mini{background:#0b2231;border:1px solid #1d3b4d;border-radius:10px;padding:8px;min-width:0}.bx span,.mini span{display:block;color:#88a8b8;font-size:9px}.bx b{display:block;font-size:14px;margin-top:3px;overflow-wrap:anywhere}.sub{font-size:10px;color:#8da8b8;line-height:1.55}.good{color:#76efc3}.warn{color:#ffe184}.bad{color:#ffaaaa}.horses,.scs,.list{display:grid;gap:7px}.horse,.sc,.item{background:#091b28;border:1px solid #1d3b4d;border-radius:11px;padding:9px}.top{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.name{font-weight:900;font-size:13px}.tag{border:1px solid #36566b;background:#0d2637;border-radius:999px;padding:3px 6px;font-size:9px;font-weight:900;white-space:nowrap}.hg{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin-top:7px}.mini{padding:6px;border:0}.mini b{display:block;font-size:10px;margin-top:2px}.queue{display:grid;gap:5px;margin-top:8px}.qr{display:grid;grid-template-columns:58px 1fr;gap:6px}.ql{font-size:9px;color:#8da8b8;font-weight:900;padding-top:4px}.chips{display:flex;flex-wrap:wrap;gap:4px}.chip{font-size:9px;border:1px solid #2a4d61;background:#0c2230;border-radius:999px;padding:3px 6px}.sc.main{border-color:#3b8068;background:#0a241f}.sp{font-size:17px;font-weight:950}.reason{font-size:10px;line-height:1.55;color:#c5d7e0;margin-top:6px}.legacy{display:none!important}.showLegacy .legacy{display:block!important}#result>.card.hero{display:none!important}#scenarioToggle{width:100%;margin-top:2px}.validatedNote{font-size:8px;color:#7897a7;margin-top:6px}
@media(max-width:560px){.g3{grid-template-columns:1fr}.hg{grid-template-columns:repeat(2,minmax(0,1fr))}.sv{padding:10px}.horse{padding:8px}}
`;document.head.appendChild(st);
function ui(){const c=$('csvState')?.closest('.card');if(c){const h=c.querySelector('h2'),m=c.querySelector('.muted');if(h)h.textContent='2. 過去走データ';if(m)m.textContent='TARGET CSVから、発走前に分かる過去走データを読み取ります。'}if($('analyzeBtn'))$('analyzeBtn').textContent='このレースを分析'}
function odds(){const C=window.ShapeCore;if(!C)return[];const o=C.parseOdds($('oddsPaste')?.value||'')?.odds||{};return Object.entries(o).map(([no,v])=>({no:String(no),od:+v})).filter(x=>x.od>0).sort((a,b)=>a.od-b.od).map((x,i)=>({...x,pop:i+1}))}
function market(){const r=odds();if(r.length<2)return null;const inv=r.map(x=>1/x.od),s=inv.reduce((a,b)=>a+b,0),p=inv.map(x=>x/s),neff=1/p.reduce((a,b)=>a+b*b,0),ratio=neff/r.length,t3=p.slice(0,3).reduce((a,b)=>a+b,0);let shape=ratio<.34?'上位人気に集中':ratio<.5?'上位人気中心':ratio<.68?'ほどよく分散':'かなり割れている',match='分析待ち';const S=window.CalibratedProbabilityState;if(S?.ready){const m=r.slice(0,3).map(x=>x.no),z=[...S.results].sort((a,b)=>b.win-a.win).slice(0,3).map(x=>String(x.no)),ov=m.filter(x=>z.includes(x)).length;match=String(z[0])===r[0].no&&ov===3?'市場と分析がほぼ一致':ov>=2?'一部一致':'ズレが大きい'}return{r,neff,ratio,t3,shape,match}}
function pace(){return [...($('rpciBars')?.querySelectorAll('.probRow')||[])].map((x,i)=>({i,p:+((x.querySelector('b')?.textContent.match(/[\d.]+/)||['0'])[0])/100})).filter(x=>Number.isFinite(x.p))}
function posMap(){const o={};for(const c of $('positionList')?.querySelectorAll('.horse')||[]){const t=c.querySelector('.horseName')?.textContent||'',m=t.match(/^(\d+)番\s*(.*)$/);if(m)o[m[1]]={name:m[2].trim(),pos:c.querySelector('.badge')?.textContent||'—'}}return o}
function escapeSet(){const s=new Set;for(const c of $('escapeList')?.querySelectorAll('.horse')||[]){const m=(c.querySelector('.horseName')?.textContent||'').match(/(\d+)番/);if(m)s.add(m[1])}return s}
function allHorses(){const S=window.CalibratedProbabilityState,M=market(),pm=posMap(),es=escapeSet(),F=window.Finish600State;if(!S?.ready)return[];const mo={},fm={};M?.r.forEach(x=>mo[x.no]=x);(F?.rows||[]).forEach(x=>fm[String(x.no)]=x);const a=S.results.map(x=>{const no=String(x.no),f=fm[no];return{no,name:x.name||'',pop:mo[no]?.pop||x.pop||99,od:mo[no]?.od||NaN,w:+x.win,t:+x.top3,pos:es.has(no)?'逃げ候補':pm[no]?.pos||'—',m3:Number(f?.finishRank)||NaN}}).sort((a,b)=>a.pop-b.pop);[...a].sort((x,y)=>y.t-x.t).forEach((h,i)=>h.pRank=i+1);return a}
function groups(H){const g={逃げ候補:[],前:[],好位:[],中団:[],後方:[]};for(const h of H){const p=String(h.pos);const k=p.includes('逃げ')?'逃げ候補':p.includes('前')?'前':p.includes('好位')?'好位':p.includes('後')?'後方':'中団';g[k].push(h)}return g}
const paceName=i=>['速い流れ','やや速い〜平均','平均〜やや遅い','遅い流れ'][i]||'別の流れ';
const paceTxt=i=>['先行馬の負荷が大きくなりやすい流れ。','ある程度流れる想定。','前半が落ち着く想定。','前が楽になりやすい想定。'][i]||'';
function benefit(i,g){const z=[],add=k=>g[k].forEach(h=>!z.includes(h)&&z.push(h));i===0?(add('中団'),add('後方'),add('好位')):i===1?(add('好位'),add('中団'),add('前')):i===2?(add('好位'),add('前'),add('中団')):(add('逃げ候補'),add('前'),add('好位'));return z.slice(0,4)}
function ensure(){const R=$('result');if(!R)return;let v=$('scenarioView');if(!v){v=document.createElement('div');v.id='scenarioView';v.innerHTML='<section id="s1" class="sv"></section><section id="s2" class="sv"></section><section id="s3" class="sv"></section><section id="s4" class="sv"></section><section id="s5" class="sv"></section><button id="scenarioToggle" class="ghost">詳細・研究用の数値を表示</button>';R.prepend(v);$('scenarioToggle').onclick=()=>{open=!open;R.classList.toggle('showLegacy',open);$('scenarioToggle').textContent=open?'詳細・研究用の数値を閉じる':'詳細・研究用の数値を表示'}}for(const c of R.querySelectorAll(':scope>.card'))if(c.id!=='finalDecisionCard')c.classList.add('legacy')}
function wave(){const w=window.TurbulenceStructureState?.wave;if(!w)return{label:'解析中',cls:'warn',text:'検証済み波乱構造を計算中'};if(!w.supported)return{label:'未検証',cls:'warn',text:w.reason||'G1〜G3のみ検証済み'};return{label:w.label,cls:w.level==='high'?'bad':w.level==='low'?'good':'warn',text:`構造スコア ${Math.round(w.score*100)}/100｜${w.action}`}}
function signature(){const S=window.CalibratedProbabilityState,F=window.Finish600State,T=window.TurbulenceStructureState;const sr=(S?.results||[]).map(x=>`${x.no}:${Number(x.win||0).toFixed(6)}:${Number(x.top3||0).toFixed(6)}`).join(';');const fr=(F?.rows||[]).map(x=>`${x.no}:${x.finishRank??''}:${Number(x.finishScore??x.score??0).toFixed(4)}`).join(';');const tw=T?.wave||{};return [S?.ready,sr,F?.ready,fr,tw.supported,tw.level,tw.label,Number(tw.score||0).toFixed(6),$('venue')?.value,$('surface')?.value,$('distance')?.value,$('fieldSize')?.value,$('grade')?.value,$('going')?.value,$('oddsPaste')?.value||'',$('rpciBars')?.textContent||''].join('|')}
function render(){if(busy)return;const sig=signature();if(sig===lastSig&&$('scenarioView'))return;busy=true;try{ui();ensure();const H=allHorses(),M=market(),pc=pace(),g=groups(H),W=wave();
if(M)$('s1').innerHTML=`<h2>① レース構造</h2><div class="g3"><div class="bx"><span>市場</span><b>${E(M.shape)}</b></div><div class="bx"><span>市場と基礎確率</span><b>${E(M.match)}</b></div><div class="bx"><span>🌪 波乱構造</span><b class="${W.cls}">${E(W.label)}</b></div></div><div class="sub" style="margin-top:7px">上位3頭支持 ${Math.round(M.t3*100)}%｜実質支持 約${M.neff.toFixed(1)}頭｜${E(W.text)}</div><div class="validatedNote">波乱構造は検証済み補助レイヤー。個別馬の勝率・M3順位は変更しません。</div>`;else $('s1').innerHTML='<h2>① レース構造</h2><div class="sub">単勝オッズ入力後に表示します。</div>';
$('s2').innerHTML=`<h2>② 今回条件</h2><div class="g3"><div class="bx"><span>コース</span><b>${E($('venue')?.value||'—')} ${E($('surface')?.value||'—')}</b></div><div class="bx"><span>距離</span><b>${E($('distance')?.value||'—')}m</b></div><div class="bx"><span>頭数・馬場</span><b>${E($('fieldSize')?.value||'—')}頭・${E($('going')?.value||'—')}</b></div></div><div class="validatedNote">コースの一般論を主観加点せず、入力された客観条件だけを表示します。</div>`;
$('s3').innerHTML=`<h2>③ 全頭チェック</h2><div class="sub">基礎確率・M3末脚順位・位置取りを分けて表示します。M3は最終着順予想ではありません。</div><div class="horses" style="margin-top:8px">${H.length?H.map(h=>`<div class="horse"><div class="top"><div><div class="name">${h.no}番 ${E(h.name)}</div><div class="sub">${h.pop}人気${Number.isFinite(h.od)?'・'+h.od.toFixed(1)+'倍':''}</div></div><span class="tag">基礎 ${h.pRank}位</span></div><div class="hg"><div class="mini"><span>勝率</span><b>${P(h.w)}</b></div><div class="mini"><span>3着内</span><b>${P(h.t)}</b></div><div class="mini"><span>M3末脚</span><b>${Number.isFinite(h.m3)?h.m3+'位':'—'}</b></div><div class="mini"><span>位置</span><b>${E(h.pos)}</b></div></div></div>`).join(''):'<div class="sub">分析計算中です。</div>'}</div><h3>位置取り</h3><div class="queue">${Object.entries(g).map(([k,a])=>`<div class="qr"><div class="ql">${k}</div><div class="chips">${a.length?a.map(h=>`<span class="chip">${h.no} ${E(h.name)}</span>`).join(''):'—'}</div></div>`).join('')}</div>`;
const s=[...pc].sort((a,b)=>b.p-a.p);$('s4').innerHTML=`<h2>④ 展開シナリオ</h2><div class="sub">数字は「その流れになる確率」。馬券の的中率ではありません。</div><div class="scs" style="margin-top:8px">${s.length?s.map((x,i)=>{const b=benefit(x.i,g);return `<div class="sc ${i===0?'main':''}"><div class="top"><div><div class="name">${i===0?'本線｜':''}${paceName(x.i)}</div><div class="sub">${paceTxt(x.i)}</div></div><div class="sp">${P(x.p)}</div></div><div class="reason"><b>位置取り上合いやすい：</b>${b.length?b.map(h=>h.no+'番'+E(h.name)).join('、'):'材料不足'}</div></div>`}).join(''):'<div class="sub">ペース分析中です。</div>'}</div>`;
const D=H.filter(h=>Number.isFinite(h.m3)&&Math.abs(h.pRank-h.m3)>=4).sort((a,b)=>Math.abs(b.pRank-b.m3)-Math.abs(a.pRank-a.m3)).slice(0,6);$('s5').innerHTML=`<h2>⑤ モデル間の食い違い</h2><div class="sub">基礎確率順位とM3末脚順位が4位以上ずれる馬だけ表示します。優劣ではなく、評価軸が違うサインです。</div><div class="list" style="margin-top:8px">${D.length?D.map(h=>`<div class="item"><div class="top"><b>${h.no}番 ${E(h.name)}</b><span class="tag">差 ${Math.abs(h.pRank-h.m3)}位</span></div><div class="reason">基礎確率 ${h.pRank}位 ｜ M3末脚 ${h.m3}位 ｜ 3着内 ${P(h.t)}</div></div>`).join(''):'<div class="sub">大きな食い違いはありません。</div>'}</div>`;
lastSig=sig;}finally{busy=false}}
function go(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>requestAnimationFrame(render),120)}
['calibrated-probability-ready','finish600-ready','turbulence-structure-ready','scenario-statistics-ready','validated-queue-ready','rsa-addons-ready','rsa-analysis-complete'].forEach(e=>addEventListener(e,go));
function bind(){ui();$('analyzeBtn')?.addEventListener('click',()=>{lastSig='';go()});go()}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();