(()=>{'use strict';
const $=x=>document.getElementById(x),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),P=x=>Number.isFinite(x)?Math.round(x*100)+'%':'—';let open=0,busy=0;
const st=document.createElement('style');st.textContent=`#scenarioView{display:grid;gap:12px;margin-top:12px}.sv{background:#081a27;border:1px solid #24475b;border-radius:16px;padding:13px}.sv h2{font-size:18px;margin:0 0 9px}.sv h3{font-size:14px;margin:12px 0 7px}.g3{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.bx,.mini{background:#0b2231;border:1px solid #1d3b4d;border-radius:11px;padding:9px}.bx span,.mini span{display:block;color:#88a8b8;font-size:9px}.bx b{display:block;font-size:15px;margin-top:3px}.sub{font-size:11px;color:#8da8b8;line-height:1.6}.good{color:#76efc3}.warn{color:#ffe184}.bad{color:#ffaaaa}.horses,.scs,.list{display:grid;gap:8px}.horse,.sc,.item{background:#091b28;border:1px solid #1d3b4d;border-radius:12px;padding:10px}.top{display:flex;justify-content:space-between;gap:8px}.name{font-weight:900;font-size:14px}.tag{border:1px solid #36566b;background:#0d2637;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:900;white-space:nowrap}.hg{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:7px}.mini{padding:6px;border:0}.mini b{font-size:11px}.factors,.chips{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.factor,.chip{font-size:10px;border:1px solid #2a4d61;background:#0c2230;border-radius:999px;padding:4px 7px}.comment,.reason{font-size:11px;line-height:1.6;color:#c5d7e0;margin-top:7px}.queue{display:grid;gap:6px}.qr{display:grid;grid-template-columns:64px 1fr;gap:6px}.ql{font-size:10px;color:#8da8b8;font-weight:900;padding-top:5px}.sc.main{border-color:#3b8068;background:#0a241f}.sp{font-size:18px;font-weight:950}.legacy{display:none!important}.showLegacy .legacy{display:block!important}#result>.card.hero{display:none!important}#scenarioToggle{width:100%;margin-top:2px}@media(max-width:560px){.g3{grid-template-columns:1fr}.hg{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(st);
function ui(){document.querySelector('.brand h1')&&(document.querySelector('.brand h1').textContent='Race Scenario Analyzer');document.querySelector('.brand small')&&(document.querySelector('.brand small').textContent='市場 × コース × 展開 × 全頭分析');document.querySelector('.brand .badge')&&(document.querySelector('.brand .badge').textContent='Scenario v1');const c=$('csvState')?.closest('.card');if(c){c.querySelector('h2').textContent='2. 過去走データ';c.querySelector('.muted').textContent='各馬の過去走から、強さ・位置取り・得意な流れ・コースとの相性を読み取ります。'}$('analyzeBtn')&&($('analyzeBtn').textContent='このレースを分析')}
function odds(){const C=window.ShapeCore;if(!C)return[];const o=C.parseOdds($('oddsPaste')?.value||'')?.odds||{};return Object.entries(o).map(([no,v])=>({no:String(no),od:+v})).filter(x=>x.od>0).sort((a,b)=>a.od-b.od).map((x,i)=>({...x,pop:i+1}))}
function market(){const r=odds();if(r.length<2)return null;const a=r.map(x=>1/x.od),s=a.reduce((x,y)=>x+y,0),p=a.map(x=>x/s),n=1/p.reduce((x,y)=>x+y*y,0),q=n/r.length,t3=p.slice(0,3).reduce((x,y)=>x+y,0);let shape=q<.34?'上位人気にかなり集中':q<.5?'上位人気中心':q<.68?'ほどよく分散':'かなり割れている',match='分析待ち';const S=window.CalibratedProbabilityState;if(S?.ready){const m=r.slice(0,3).map(x=>x.no),z=[...S.results].sort((a,b)=>b.win-a.win).slice(0,3).map(x=>String(x.no)),ov=m.filter(x=>z.includes(x)).length;match=String(z[0])===r[0].no&&ov===3?'市場と分析がほぼ一致':ov>=2?'市場と分析に少しズレ':'市場と分析のズレ大'}return{r,n,q,t3,shape,match}}
function pace(){return [...($('rpciBars')?.querySelectorAll('.probRow')||[])].map((x,i)=>({i,p:+((x.querySelector('b')?.textContent.match(/[\d.]+/)||['0'])[0])/100}))}
function pos(){const o={};for(const c of $('positionList')?.querySelectorAll('.horse')||[]){const t=c.querySelector('.horseName')?.textContent||'',m=t.match(/^(\d+)番\s*(.*)$/);if(m)o[m[1]]={name:m[2].trim(),p:c.querySelector('.badge')?.textContent||'—'}}return o}
function escSet(){const s=new Set;for(const c of $('escapeList')?.querySelectorAll('.horse')||[]){const m=(c.querySelector('.horseName')?.textContent||'').match(/(\d+)番/);m&&s.add(m[1])}return s}
function card(id,name){for(const c of $(id)?.querySelectorAll('.horse')||[])if((c.querySelector('.horseName')?.textContent||'').includes(name))return c;return null}
function factor(name,label){const c=card('integratedViewList',name);if(!c)return{m:'—',v:NaN};for(const f of c.querySelectorAll('.ivFactor'))if((f.querySelector('span')?.textContent||'').includes(label)){const t=f.querySelector('b')?.textContent||'',m=t.replace('−','-').match(/([+\-]?\d+(?:\.\d+)?)pt/),v=m?+m[1]:NaN;return{m:Number.isFinite(v)?v>=.5?'◎':v<=-.5?'△':'○':'—',v}}return{m:'—',v:NaN}}
function label(name){const t=card('integratedViewList',name)?.querySelector('.ivHero')?.textContent||'';return t.includes('追い風')||t.includes('好転')?'合う':t.includes('向かい風')?'やや不利':t.includes('据え置き')?'標準':'確認中'}
function comment(name){return card('integratedViewList',name)?.querySelector('.ivOneLine')?.textContent?.trim()||'過去走と今回条件を合わせて分析中です。'}
function horses(){const S=window.CalibratedProbabilityState,M=market(),pm=pos(),es=escSet();if(!S?.ready)return[];const mp={};M?.r.forEach(x=>mp[x.no]=x);const a=S.results.map(x=>{const no=String(x.no),name=x.name,A=window.AbilityOpponentState?.resultsByName?.[name],f={c:factor(name,'コース'),d:factor(name,'条件替わり'),p:factor(name,'展開')};return{no,name,pop:mp[no]?.pop||x.pop||99,od:mp[no]?.od||NaN,w:+x.win,t:+x.top3,ab:A,ability:A?(A.grade==='A'?'上位':A.grade==='B'?'中位':'下位'):'—',fit:label(name),pos:pm[no]?.p||'—',esc:es.has(no),f,comment:comment(name)}}).sort((a,b)=>a.pop-b.pop);[...a].sort((x,y)=>y.t-x.t).forEach((h,i)=>h.rank=i+1);return a}
function range(h){return h.w>=.15&&h.t>=.4?'勝ち切り〜3着内':h.w>=.09&&h.t>=.3?'1着まで / 上位圏':h.t>=.22?'上位〜中位':h.t>=.13?'展開次第で上位':'上振れ待ち'}
function groups(H){const g={逃げ候補:[],前:[],好位:[],中団:[],後方:[]};H.forEach(h=>{let k=h.esc?'逃げ候補':h.pos.includes('前')?'前':h.pos.includes('好位')?'好位':h.pos.includes('後')?'後方':'中団';g[k].push(h)});Object.values(g).forEach(a=>a.sort((x,y)=>y.t-x.t));return g}
const paceName=i=>['速い流れ','やや速い〜平均','平均〜やや遅い','遅い流れ'][i]||'別の流れ',paceTxt=i=>['先行馬が競り合い、前の負荷が大きくなる展開。中団〜差しに浮上余地。','ある程度流れて、好位と中団の両方にチャンス。','前半が落ち着き、好位〜前の馬が運びやすい展開。','前が楽になり、逃げ・先行が残りやすい展開。'][i]||'';
function benefit(i,g){const z=[],add=k=>g[k].forEach(h=>!z.includes(h)&&z.push(h));i===0?(add('中団'),add('後方'),add('好位')):i===1?(add('好位'),add('中団'),add('前')):i===2?(add('好位'),add('前'),add('中団')):(add('逃げ候補'),add('前'),add('好位'));return z.slice(0,4)}
function issues(h,pc){const a=[];[['c','コース'],['d','条件替わり'],['p','展開']].forEach(([k,l])=>Number.isFinite(h.f[k].v)&&h.f[k].v<=-.5&&a.push(l+'がやや向かい風'));const fast=(pc[0]?.p||0)+(pc[1]?.p||0),slow=pc[3]?.p||0;if((h.esc||h.pos.includes('前'))&&fast>=.45)a.push('速い流れになると前で負荷');if(h.pos.includes('後')&&slow>=.28)a.push('流れが落ち着くと差し届かない可能性');if(h.ab?.rank&&h.ab.rank-h.pop>=3)a.push('人気ほど能力順位は高くない');return[...new Set(a)].slice(0,3)}
const profiles={東京:['直線が長い','大回り','長く脚を使える馬'],中山:['直線が短い','坂がきつめ','前〜好位で立ち回れる馬'],京都:['直線は標準〜長め','下りを使う','リズム良く加速できる馬'],阪神:['直線は標準〜長め','坂あり','持続力のある馬'],中京:['直線が長め','坂あり','好位〜中団で脚を残せる馬'],新潟:['直線が長い','左回り','末脚を長く使える馬'],福島:['小回り','直線が短い','位置取りの良い馬'],小倉:['小回り','直線が短い','機動力のある馬'],札幌:['小回り寄り','直線が短い','早めに位置を取れる馬'],函館:['小回り','直線が短い','前で粘れる馬']};
function ensure(){const R=$('result');if(!R)return;let v=$('scenarioView');if(!v){v=document.createElement('div');v.id='scenarioView';v.innerHTML='<section id="s1" class="sv"></section><section id="s2" class="sv"></section><section id="s3" class="sv"></section><section id="s4" class="sv"></section><section id="s5" class="sv"></section><section id="s6" class="sv"></section><button id="scenarioToggle" class="ghost">検証用の詳細な数値を表示</button>';R.prepend(v);$('scenarioToggle').onclick=()=>{open=!open;R.classList.toggle('showLegacy',open);$('scenarioToggle').textContent=open?'検証用の詳細な数値を閉じる':'検証用の詳細な数値を表示'}}for(const c of R.querySelectorAll(':scope>.card'))c.classList.add('legacy')}
function render(){if(busy)return;busy=1;try{ui();ensure();const H=horses(),M=market(),pc=pace(),g=groups(H);if(M){const max=pc.length?Math.max(...pc.map(x=>x.p)):0,fi=issues(H.find(x=>x.pop===1)||{},pc);let r=M.q>.58||max<.45||fi.length>=2?'大':M.q<.38&&max>.55&&!fi.length?'小':'中';$('s1').innerHTML=`<h2>① レースの見立て</h2><div class="g3"><div class="bx"><span>オッズから見た市場</span><b>${E(M.shape)}</b></div><div class="bx"><span>人気と分析</span><b>${E(M.match)}</b></div><div class="bx"><span>荒れる余地</span><b class="${r==='大'?'bad':r==='小'?'good':'warn'}">${r}</b></div></div><div class="sub" style="margin-top:8px">上位3頭支持 ${Math.round(M.t3*100)}% / 人気は実質約 ${M.n.toFixed(1)}頭に分散。買い判定ではなく市場の形を表示します。</div>`}else $('s1').innerHTML='<h2>① レースの見立て</h2><div class="sub">単勝オッズ入力後に表示します。</div>';
const C=profiles[$('venue')?.value]||['コース形態を確認','位置取りが重要','今回条件に合う馬'];$('s2').innerHTML=`<h2>② コース形態まとめ</h2><div class="g3"><div class="bx"><span>形</span><b>${E(C[0])}</b></div><div class="bx"><span>特徴</span><b>${E(C[1])}</b></div><div class="bx"><span>有利になりやすい</span><b>${E(C[2])}</b></div></div><div class="sub" style="margin-top:8px">${E($('venue')?.value)} ${E($('surface')?.value)}${E($('distance')?.value)}m。各馬のコース相性は下の全頭チェックに反映します。</div>`;
$('s3').innerHTML=`<h2>③ 全頭チェック</h2><div class="sub">重要な分析はタップせず全頭表示します。</div><div class="horses" style="margin-top:8px">${H.length?H.map(h=>`<div class="horse"><div class="top"><div><div class="name">${h.no}番 ${E(h.name)}</div><div class="sub">${h.pop}人気${Number.isFinite(h.od)?'・'+h.od.toFixed(1)+'倍':''}</div></div><span class="tag">${E(range(h))}</span></div><div class="hg"><div class="mini"><span>強さ</span><b>${E(h.ability)}</b></div><div class="mini"><span>今回</span><b>${E(h.fit)}</b></div><div class="mini"><span>位置</span><b>${E(h.esc?'逃げ候補':h.pos)}</b></div><div class="mini"><span>勝つ確率</span><b>${P(h.w)}</b></div><div class="mini"><span>3着内</span><b>${P(h.t)}</b></div></div><div class="factors"><span class="factor">コース ${h.f.c.m}</span><span class="factor">条件 ${h.f.d.m}</span><span class="factor">展開 ${h.f.p.m}</span></div><div class="comment">${E(h.comment)}</div></div>`).join(''):'<div class="sub">分析計算中です。</div>'}</div><h3>位置取り図</h3><div class="queue">${Object.entries(g).map(([k,a])=>`<div class="qr"><div class="ql">${k}</div><div class="chips">${a.length?a.map(h=>`<span class="chip">${h.no} ${E(h.name)}</span>`).join(''):'—'}</div></div>`).join('')}</div>`;
const s=[...pc].sort((a,b)=>b.p-a.p);$('s4').innerHTML=`<h2>④ シナリオ別</h2><div class="sub">数字は「その流れになる確率」。馬券の的中率ではありません。</div><div class="scs" style="margin-top:8px">${s.length?s.map((x,i)=>{const b=benefit(x.i,g);return `<div class="sc ${i===0?'main':''}"><div class="top"><div><div class="name">${i===0?'本命シナリオ｜':''}${paceName(x.i)}</div><div class="sub">${paceTxt(x.i)}</div></div><div class="sp">${P(x.p)}</div></div><div class="comment"><b>浮上しやすい：</b>${b.length?b.map(h=>h.no+'番'+E(h.name)).join('、'):'材料不足'}</div></div>`}).join(''):'<div class="sub">ペース分析中です。</div>'}</div>`;
const F=H.filter(h=>h.pop<=3);$('s5').innerHTML=`<h2>⑤ 人気馬の不安材料</h2><div class="list">${F.length?F.map(h=>{const z=issues(h,pc),lv=z.length>=2?'不安あり':z.length?'注意':'不安少なめ';return `<div class="item"><div class="top"><b>${h.no}番 ${E(h.name)}｜${h.pop}人気</b><span class="${z.length>=2?'bad':z.length?'warn':'good'}">${lv}</span></div><div class="reason">${z.length?z.map(x=>'・'+E(x)).join('<br>'):'・今の分析では大きな不安材料は見つかっていません。'}</div></div>`}).join(''):'<div class="sub">人気順を確認中です。</div>'}</div>`;
const U=H.filter(h=>h.pop>=4).sort((a,b)=>(b.pop-b.rank)*1.5+b.t*10+(b.fit==='合う'?2:0)-(a.pop-a.rank)*1.5-a.t*10-(a.fit==='合う'?2:0)).slice(0,4);$('s6').innerHTML=`<h2>⑥ 逆転候補</h2><div class="sub">買い推奨ではなく、人気より上に来る余地を整理します。</div><div class="list" style="margin-top:8px">${U.length?U.map(h=>`<div class="item"><div class="top"><b>${h.no}番 ${E(h.name)}</b><span class="tag">${h.pop}人気</span></div><div class="reason">・3着内評価 ${h.rank}番手 / 人気 ${h.pop}番手<br>・強さ ${E(h.ability)} / 今回 ${E(h.fit)}<br>・3着内 ${P(h.t)} / 勝つ確率 ${P(h.w)}</div></div>`).join(''):'<div class="sub">候補計算中です。</div>'}</div>`}finally{busy=0}}
function go(){[100,350,800,1500,2800,4200].forEach(t=>setTimeout(render,t))}['calibrated-probability-ready','ability-opponent-ready','joint-pair-probability-ready','rsa-addons-ready'].forEach(e=>addEventListener(e,go));addEventListener('load',()=>{ui();$('analyzeBtn')?.addEventListener('click',go);go()});document.readyState!=='loading'&&(ui(),$('analyzeBtn')?.addEventListener('click',go),go());
})();
