(()=>{'use strict';
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=p=>Number.isFinite(p)?`${Math.round(p*100)}%`:'—';let busy=false;
function byNo(state){const m={};for(const x of state?.results||[])if(x.no!==undefined&&x.no!==null)m[String(x.no)]=x;return m}
function independentLabel(){const I=window.IndependentAnalysisState;if(!I?.ready)return null;const rows=(I.results||[]).filter(x=>Number.isFinite(x.marketRank));if(!rows.length)return null;const market=[...rows].sort((a,b)=>a.marketRank-b.marketRank).slice(0,3).map(x=>String(x.no)),ability=[...rows].sort((a,b)=>a.abilityRank-b.abilityRank).slice(0,3).map(x=>String(x.no)),ov=market.filter(x=>ability.includes(x)).length,same=market[0]===ability[0];return same&&ov===3?'市場と地力がほぼ一致':ov>=2?'市場と地力に少しズレ':'市場と地力のズレ大'}
function patchOverview(){const lab=independentLabel();if(!lab)return;const boxes=[...document.querySelectorAll('#s1>.g3 .bx')];if(boxes[1]){const s=boxes[1].querySelector('span'),b=boxes[1].querySelector('b');if(s)s.textContent='市場と地力';if(b)b.textContent=lab}const sig=[...document.querySelectorAll('#raceHeroV2 .rhSignal')];for(const x of sig){const s=x.querySelector('span');if((s?.textContent||'').includes('人気と分析')){s.textContent='市場と地力';const b=x.querySelector('b');if(b)b.innerHTML=`<i class="dot"></i>${E(lab)}`}}
const R=window.RaceCoherentProbabilityState;if(R?.ready){let note=document.getElementById('raceCoherentNote');if(!note){note=document.createElement('div');note.id='raceCoherentNote';note.className='sub';note.style.marginTop='8px';document.getElementById('s1')?.appendChild(note)}if(note)note.textContent=`レース内で確率整合済み：勝率合計 ${Math.round(R.sums.win*100)}% / 連対率合計 ${Math.round(R.sums.top2*100)}% / 3着内率合計 ${Math.round(R.sums.top3*100)}%`}}
function patchHorseCards(){const R=window.RaceCoherentProbabilityState;if(!R?.ready)return;const m=byNo(R);for(const c of document.querySelectorAll('#s3 .horse')){const no=(c.querySelector('.name')?.textContent||'').match(/^(\d+)番/)?.[1];const x=m[String(no||'')];if(!x)continue;for(const mini of c.querySelectorAll('.mini')){const l=mini.querySelector('span')?.textContent||'',b=mini.querySelector('b');if(!b)continue;if(l.includes('勝つ確率'))b.textContent=pct(x.win);if(l.includes('3着内'))b.textContent=pct(x.top3)}let p=c.querySelector('.statCoherentPill');if(!p){p=document.createElement('span');p.className='factor statCoherentPill';const f=c.querySelector('.factors');if(f)f.appendChild(p)}if(p)p.textContent='確率：レース内整合済み'} }
function patchPopular(){const I=window.IndependentAnalysisState;if(!I?.ready)return;const m=byNo(I);for(const item of document.querySelectorAll('#s5 .item')){const no=(item.querySelector('b')?.textContent||'').match(/^(\d+)番/)?.[1],x=m[String(no||'')];if(!x)continue;let r=item.querySelector('.independentRankLine');if(!r){r=document.createElement('div');r.className='reason independentRankLine';item.appendChild(r)}r.innerHTML=`・市場を使わない地力順位 <b>${x.abilityRank}位</b>（人気 ${x.marketRank}位）`}}
function patchUpset(){const I=window.IndependentAnalysisState,R=window.RaceCoherentProbabilityState,box=document.getElementById('s6');if(!I?.ready||!box)return;const rm=byNo(R),c=(I.results||[]).filter(x=>Number.isFinite(x.marketRank)&&Number.isFinite(x.abilityRank)&&x.marketRank-x.abilityRank>=2).sort((a,b)=>(b.marketRank-b.abilityRank)-(a.marketRank-a.abilityRank)||a.abilityRank-b.abilityRank).slice(0,5);const h=box.querySelector('h2');if(h)h.textContent='⑦ 逆転候補';let sub=box.querySelector(':scope>.sub');if(sub)sub.textContent='市場を使わない地力順位が、人気順位より2つ以上上の馬だけを表示します。買い推奨ではありません。';let list=box.querySelector('.list');if(!list){list=document.createElement('div');list.className='list';box.appendChild(list)}if(!c.length){list.innerHTML='<div class="item"><div class="reason">明確な逆転候補なし。市場人気と市場を使わない地力順位の差が小さいレースです。</div></div>';return}list.innerHTML=c.map(x=>{const q=rm[String(x.no)]||{},gap=x.marketRank-x.abilityRank;return `<div class="item"><div class="top"><b>${E(x.no)}番 ${E(x.name)}</b><span class="tag">${x.marketRank}人気</span></div><div class="reason">・市場を使わない地力 <b>${x.abilityRank}位</b> / 人気 ${x.marketRank}位（${gap}つ上）<br>・レース整合勝率 ${pct(q.win)} / 3着内 ${pct(q.top3)}<br>・コース・条件・展開は全頭チェックと隊列で確認</div></div>`}).join('')}
function patch(){if(busy)return;busy=true;try{patchOverview();patchHorseCards();patchPopular();patchUpset()}finally{busy=false}}
function go(){[120,350,750,1400,2600,4300].forEach(t=>setTimeout(patch,t))}
['race-coherent-probability-ready','independent-analysis-ready','ability-opponent-ready','calibrated-probability-ready','rsa-addons-ready'].forEach(e=>addEventListener(e,go));addEventListener('load',go);document.getElementById('analyzeBtn')?.addEventListener('click',go);document.getElementById('applyOddsBtn')?.addEventListener('click',go);if(document.readyState!=='loading')go();
})();
