(()=>{'use strict';
const $=id=>document.getElementById(id),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),sigmoid=z=>1/(1+Math.exp(-z)),logit=p=>Math.log(clamp(p,1e-8,1-1e-8)/(1-clamp(p,1e-8,1-1e-8)));
function project(base,target,lower){const n=base.length,L=lower||Array(n).fill(0),cap=L.reduce((s,v)=>s+v,0);target=clamp(target,cap,n);const r=base.map((p,i)=>{const l=clamp(Number(L[i])||0,0,.999999),den=1-l;return den<=1e-9 ? 0.5 : clamp((clamp(Number(p)||0,0,1)-l)/den,1e-7,1-1e-7)});const sum=lam=>r.reduce((s,v,i)=>{const l=clamp(Number(L[i])||0,0,.999999);return s+l+(1-l)*sigmoid(logit(v)+lam)},0);let lo=-30,hi=30;for(let k=0;k<90;k++){const mid=(lo+hi)/2;if(sum(mid)>target)hi=mid;else lo=mid}const lam=(lo+hi)/2;return r.map((v,i)=>{const l=clamp(Number(L[i])||0,0,.999999);return l+(1-l)*sigmoid(logit(v)+lam)})}
function coherent(){const S=window.CalibratedProbabilityState;if(!S?.ready||!(S.results||[]).length)return;const rows=S.results.map(x=>({...x,rawWin:Number(x.win),rawTop2:Number(x.top2),rawTop3:Number(x.top3)})),n=rows.length;const w=project(rows.map(x=>x.rawWin),Math.min(1,n));const t2=project(rows.map(x=>x.rawTop2),Math.min(2,n),w);const t3=project(rows.map(x=>x.rawTop3),Math.min(3,n),t2);rows.forEach((x,i)=>{x.win=w[i];x.top2=t2[i];x.top3=t3[i]});window.RaceCoherentProbabilityState={ready:true,version:'v1-logit-projection',results:rows,resultsByName:Object.fromEntries(rows.map(x=>[x.name,x])),rawSums:{win:rows.reduce((s,x)=>s+x.rawWin,0),top2:rows.reduce((s,x)=>s+x.rawTop2,0),top3:rows.reduce((s,x)=>s+x.rawTop3,0)},sums:{win:rows.reduce((s,x)=>s+x.win,0),top2:rows.reduce((s,x)=>s+x.top2,0),top3:rows.reduce((s,x)=>s+x.top3,0)}};window.dispatchEvent(new CustomEvent('race-coherent-probability-ready'))}
function oddsRanks(){const C=window.ShapeCore;if(!C)return{};const o=C.parseOdds($('oddsPaste')?.value||'')?.odds||{};const a=Object.entries(o).map(([no,v])=>({no:String(no),od:Number(v)})).filter(x=>x.od>0).sort((a,b)=>a.od-b.od);const out={};a.forEach((x,i)=>out[x.no]=i+1);return out}
function independent(){const A=window.AbilityOpponentState;if(!A?.ready||!(A.results||[]).length)return;const market=oddsRanks(),rows=[...A.results].sort((a,b)=>Number(a.rank||999)-Number(b.rank||999)).map((x,i)=>{const no=String(x.no||''),abilityRank=Number(x.rank)||i+1,marketRank=Number(market[no]);return{...x,no,abilityRank,marketRank:Number.isFinite(marketRank)?marketRank:null,gap:Number.isFinite(marketRank)?marketRank-abilityRank:null}});window.IndependentAnalysisState={ready:true,version:'ability-opponent-v3-market-free',results:rows,resultsByName:Object.fromEntries(rows.map(x=>[x.name,x]))};window.dispatchEvent(new CustomEvent('independent-analysis-ready'))}
function guardDistance(e){const d=Number($('distance')?.value);if(Number.isFinite(d)&&d>=1000&&d<=3600)return;const el=$('distance');if(el){el.style.borderColor='#ff7777';el.style.boxShadow='0 0 0 3px rgba(255,119,119,.16)'}let m=$('statInputGuard');if(!m&&el){m=document.createElement('div');m.id='statInputGuard';m.style.cssText='margin-top:6px;color:#ffb0b0;font-size:11px;font-weight:800;line-height:1.5';el.insertAdjacentElement('afterend',m)}if(m)m.textContent='距離はJRA平地の想定範囲 1000〜3600m で入力してください。範囲外では解析しません。';if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}return false}
function clearGuard(){const d=Number($('distance')?.value),el=$('distance'),m=$('statInputGuard');if(Number.isFinite(d)&&d>=1000&&d<=3600){if(el){el.style.borderColor='';el.style.boxShadow=''}if(m)m.remove()}}
function bind(){const b=$('analyzeBtn');if(b&&!b.dataset.statGuard){b.dataset.statGuard='1';b.addEventListener('click',e=>{if(guardDistance(e)===false)return},true)}$('distance')?.addEventListener('input',clearGuard);clearGuard();setTimeout(coherent,100);setTimeout(independent,180)}
window.addEventListener('calibrated-probability-ready',coherent);window.addEventListener('ability-opponent-ready',independent);window.addEventListener('race-coherent-probability-ready',independent);window.addEventListener('rsa-addons-ready',()=>{coherent();independent()});if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
