(()=>{'use strict';
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let busy=false;
const css=document.createElement('style');css.textContent=`
#raceAtGlanceV4{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin:8px 0 0}.rag4{min-width:0;background:#0a2130;border:1px solid #2b5266;border-radius:12px;padding:9px 8px}.rag4 span{display:block;color:#7899aa;font-size:8px;margin-bottom:4px}.rag4 b{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rag4.good b{color:#66e4b4}.rag4.warn b{color:#f0d06d}.rag4.bad b{color:#ff9098}.rtHorse .rtNo{display:grid!important;place-items:center!important;width:100%;height:100%;font-size:12px!important;color:#f4fbff!important;font-weight:950!important;position:relative;z-index:5}.rtHorse b,.rtHorse small{display:none!important}.uiMovedTechnical{display:none!important}.showLegacy .uiMovedTechnical{display:block!important}.qPositionTextHidden{display:none!important}
@media(max-width:700px){#raceAtGlanceV4{grid-template-columns:repeat(2,minmax(0,1fr))}.rag4:last-child{grid-column:1/-1}}
`;document.head.appendChild(css);
function text(el){return (el?.textContent||'').replace(/\s+/g,' ').trim()}
function topCard(){const s1=$('s1'),hero=$('raceHeroV2');if(!s1||!hero)return;const boxes=[...s1.querySelectorAll(':scope>.g3 .bx')];if(boxes.length<3)return;const market=text(boxes[0]?.querySelector('b'))||'分析中',match=text(boxes[1]?.querySelector('b'))||'分析中',rough=text(boxes[2]?.querySelector('b'))||'—';const sc=[...document.querySelectorAll('#s4 .sc')].map(c=>({p:parseFloat(text(c.querySelector('.sp')))||0,n:text(c.querySelector('.name')).replace('本命シナリオ｜','').replace(/^A\s*本線｜?/,'').trim()})).sort((a,b)=>b.p-a.p)[0];let pressure=text(document.querySelector('#sQueue .qSummary .qBox:first-child b'));if(!pressure){const m=text($('sQueue')).match(/前の競り合い\s*(高|中|低)/);pressure=m?m[1]:'—'}const issueN=[...document.querySelectorAll('#s5 .item')].slice(0,3).filter(x=>/不安あり|注意|向かい風|負荷|能力順位/.test(text(x))).length;let box=$('raceAtGlanceV4');if(!box){box=document.createElement('div');box.id='raceAtGlanceV4';hero.insertAdjacentElement('afterend',box)}const mc=match.includes('ズレ大')?'bad':match.includes('少し')?'warn':'good',rc=rough.includes('大')?'bad':rough.includes('小')?'good':'warn',pc=pressure==='高'?'warn':pressure==='低'?'good':'';box.innerHTML=`<div class="rag4"><span>市場</span><b>${E(market)}</b></div><div class="rag4 ${mc}"><span>人気通り度</span><b>${E(match)}</b></div><div class="rag4 ${rc}"><span>荒れる余地</span><b>${E(rough)}</b></div><div class="rag4 ${pc}"><span>前の競り合い</span><b>${E(pressure)}</b></div><div class="rag4 ${issueN?'warn':'good'}"><span>本線 / 人気馬</span><b>${E(sc?`${sc.n||'本線'} ${Math.round(sc.p)}%`:'分析中')}・${issueN?`${issueN}頭注意`:'注意少なめ'}</b></div>`}
function moveTechnical(){const s1=$('s1');if(!s1)return;const nodes=[...s1.querySelectorAll('div,p,small')].filter(x=>{const t=text(x);return t.includes('レース内で確率整合済み')||t.includes('勝率 100% / 連対 200% / 3着内 300%')}).sort((a,b)=>text(a).length-text(b).length);if(nodes[0])nodes[0].classList.add('uiMovedTechnical','legacy')}
function simplifyQueue(){const q=$('sQueue');if(!q)return;const lanes=q.querySelector('.qLanes');if(lanes)lanes.classList.add('qPositionTextHidden');for(const h of q.querySelectorAll('h3'))if(text(h)==='位置取り予想')h.classList.add('qPositionTextHidden')}
function ensureMapNumbers(){for(const h of document.querySelectorAll('#qRealTrack .rtHorse')){let no=h.dataset?.no||'';if(!no){const m=text(h.querySelector('b')).match(/^(\d{1,2})/);if(m)no=m[1]}if(!no)continue;let s=h.querySelector('.rtNo');if(!s){s=document.createElement('span');s.className='rtNo';h.prepend(s)}s.textContent=no}}
function syncPositions(){const S=window.ValidatedQueueState;if(!S?.ready||!S.byNo)return;for(const card of document.querySelectorAll('#s3 .horse')){const m=text(card.querySelector('.name')).match(/(\d{1,2})番/);if(!m)continue;const r=S.byNo[m[1]];if(!r?.position||r.position==='—')continue;const mini=[...card.querySelectorAll('.mini')].find(x=>text(x.querySelector('span')).includes('位置'));if(mini?.querySelector('b'))mini.querySelector('b').textContent=r.position}}
function run(){if(busy)return;busy=true;try{topCard();moveTechnical();simplifyQueue();ensureMapNumbers();syncPositions()}finally{busy=false}}
function schedule(){[0,80,180,360,700,1200,2200,3800].forEach(t=>setTimeout(run,t))}
['validated-queue-ready','scenario-statistics-ready','calibrated-probability-ready','rsa-addons-ready'].forEach(ev=>addEventListener(ev,schedule));addEventListener('load',schedule);document.addEventListener('click',e=>{if(e.target?.id==='analyzeBtn'||e.target?.id==='parseCsvBtn')schedule()});const mo=new MutationObserver(()=>{clearTimeout(window.__uiFixV4);window.__uiFixV4=setTimeout(run,70)});if(document.readyState==='loading')addEventListener('DOMContentLoaded',()=>{mo.observe(document.body,{childList:true,subtree:true});schedule()},{once:true});else{mo.observe(document.body,{childList:true,subtree:true});schedule()}
})();