(()=>{'use strict';
const BUILD='20261009v4a',DB_NAME='rsa-v4-state',STORE='state',KEY='draft',FIELD_KEY='rsa-v4-fields-v1';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=()=>({version:2,race:{raceDate:'',venue:'',raceName:'',fieldSize:'',surface:'芝',distance:'',grade:'G1',going:'良'},odds:'',csv:null,results:null,dirty:false,updatedAt:0});
let state=defaults(),db=null,saveTimer=null,activeTab='summary',horsePage=0,busy=false;
const raceIds=['raceDate','venue','raceName','fieldSize','surface','distance','grade','going'];
function pct(v){return Number.isFinite(Number(v))?Math.round(Number(v)*100)+'%':'—'}
function num(v){const n=Number(v);return Number.isFinite(n)?n:NaN}
function countOdds(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(x=>/^\d+\s+\d+(?:\.\d+)?$/.test(x)).length}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbGet(){return new Promise((resolve,reject)=>{if(!db)return resolve(null);const r=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
function dbPut(value){return new Promise((resolve,reject)=>{if(!db)return resolve();const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function dbDelete(){return new Promise((resolve,reject)=>{if(!db)return resolve();const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function syncFieldBackup(){try{localStorage.setItem(FIELD_KEY,JSON.stringify({race:state.race,odds:state.odds,dirty:state.dirty,updatedAt:Date.now()}))}catch{}}
function restoreFieldBackup(){try{return JSON.parse(localStorage.getItem(FIELD_KEY)||'null')}catch{return null}}
async function saveNow(){state.updatedAt=Date.now();syncFieldBackup();try{await dbPut(state);$('persistStatus').textContent='端末保存済'}catch(e){console.warn('v4 save',e);$('persistStatus').textContent='入力は簡易保存済'}}
function scheduleSave(){clearTimeout(saveTimer);syncFieldBackup();$('persistStatus').textContent='保存中…';saveTimer=setTimeout(saveNow,120)}
function setDirty(){if(state.results){state.dirty=true;$('resultFresh').textContent='要再解析';$('resultFresh').className='pill muted'}scheduleSave()}
function applyStateToForm(){raceIds.forEach(id=>{const el=$(id);if(el)el.value=state.race[id]??''});$('oddsPaste').value=state.odds||'';$('oddsCount').textContent=countOdds(state.odds)+'頭';if(state.csv?.name){$('csvName').textContent=state.csv.name;$('csvState').textContent='端末保存済';$('csvState').className='pill good'}else{$('csvName').textContent='TARGET CSVを選択';$('csvState').textContent='未選択';$('csvState').className='pill muted'}renderResult()}
function hydrate(saved){const f=restoreFieldBackup();state=defaults();if(f?.race)Object.assign(state.race,f.race);if(typeof f?.odds==='string')state.odds=f.odds;if(saved){state={...state,...saved,race:{...state.race,...(saved.race||{})}}}state.dirty=!!state.dirty}
function bindInputs(){raceIds.forEach(id=>{$(id)?.addEventListener('input',()=>{state.race[id]=$(id).value;setDirty()});$(id)?.addEventListener('change',()=>{state.race[id]=$(id).value;setDirty()})});$('oddsPaste').addEventListener('input',()=>{state.odds=$('oddsPaste').value;$('oddsCount').textContent=countOdds(state.odds)+'頭';setDirty()});$('csvFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;state.csv={name:file.name,type:file.type||'text/csv',size:file.size,lastModified:file.lastModified||Date.now(),blob:file.slice(0,file.size,file.type||'text/csv')};$('csvName').textContent=file.name;$('csvState').textContent='端末保存済';$('csvState').className='pill good';setDirty();await saveNow()});$('clearCsvBtn').addEventListener('click',async()=>{state.csv=null;$('csvFile').value='';$('csvName').textContent='TARGET CSVを選択';$('csvState').textContent='未選択';$('csvState').className='pill muted';setDirty();await saveNow()});$('clearAllBtn').addEventListener('click',async()=>{if(!confirm('このレースの保存データを削除しますか？'))return;clearTimeout(saveTimer);state=defaults();try{localStorage.removeItem(FIELD_KEY)}catch{}await dbDelete();applyStateToForm();$('persistStatus').textContent='保存データなし';$('errorBox').classList.add('hidden')});$('analyzeBtn').addEventListener('click',analyze);$('resultTabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;activeTab=b.dataset.tab;horsePage=0;renderResult()});$('resultPanel').addEventListener('click',e=>{if(e.target.closest('[data-prev]')){horsePage=Math.max(0,horsePage-1);renderResult()}if(e.target.closest('[data-next]')){horsePage++;renderResult()}})}
function validate(){const missing=[];if(!state.race.venue)missing.push('競馬場');if(!state.race.fieldSize)missing.push('頭数');if(!state.race.distance)missing.push('距離');if(!state.csv?.blob)missing.push('過去走CSV');if(countOdds(state.odds)<2)missing.push('単勝オッズ');return missing}
function waitFor(fn,timeout=20000,interval=80){return new Promise((resolve,reject)=>{const started=Date.now();const tick=()=>{let v=false;try{v=fn()}catch{}if(v)return resolve(v);if(Date.now()-started>timeout)return reject(new Error('処理がタイムアウトしました'));setTimeout(tick,interval)};tick()})}
function fire(w,el,type){el.dispatchEvent(new w.Event(type,{bubbles:true}))}
function setEngineValue(w,d,id,value){const el=d.getElementById(id);if(!el)return;el.value=value??'';fire(w,el,'input');fire(w,el,'change')}
async function bootEngine(){const host=$('engineHost');host.replaceChildren();const frame=document.createElement('iframe');frame.tabIndex=-1;frame.src=`v3q.html?engine=v4&build=${BUILD}&t=${Date.now()}`;host.appendChild(frame);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('分析エンジンを起動できませんでした')),15000);frame.addEventListener('load',()=>{clearTimeout(t);resolve()},{once:true})});const w=frame.contentWindow,d=frame.contentDocument;await waitFor(()=>w.RSAAddonHealth?.ready===true,30000);return{frame,w,d}}
async function feedEngine(engine){const{w,d}=engine;for(const id of raceIds)setEngineValue(w,d,id,state.race[id]);const input=d.getElementById('csvFile');if(!input)throw new Error('CSV入力を準備できませんでした');const bytes=await state.csv.blob.arrayBuffer();const file=new w.File([bytes],state.csv.name,{type:state.csv.type||'text/csv',lastModified:state.csv.lastModified||Date.now()});const dt=new w.DataTransfer();dt.items.add(file);input.files=dt.files;fire(w,input,'change');await waitFor(()=>/^解析済\s+\d+頭/.test(d.getElementById('csvState')?.textContent||''),20000);const odds=d.getElementById('oddsPaste');odds.value=state.odds;fire(w,odds,'input');d.getElementById('applyOddsBtn')?.click();await waitFor(()=>/反映/.test(d.getElementById('oddsInfo')?.textContent||''),12000)}
function engineDiagnostic(w){const t=w.RSAAnalysisTransitionState||{};return{transition:t.status||'',missing:t.missing||[],calibrated:!!w.CalibratedProbabilityState?.ready,scenario:!!w.ScenarioStatisticsState?.ready,legacyM3:!!w.Finish600State?.ready,final:!!w.FinalDecisionState?.ready,wave:!!w.TurbulenceStructureState?.ready}}
function localDisagreements(horses){return horses.filter(h=>Number.isFinite(h.m3)).map(h=>{const delta=h.pRank-h.m3;return{no:h.no,name:h.name,pRank:h.pRank,m3Rank:h.m3,delta,status:delta>0?'末脚↑ / 基礎確率↓':delta<0?'基礎確率↑ / 末脚↓':'一致'}}).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta))}
function extractEngine(engine,m3State){const{w,d}=engine;const probs=(w.CalibratedProbabilityState?.results||[]).map(x=>({no:String(x.no),name:String(x.name||''),win:num(x.win),top2:num(x.top2),top3:num(x.top3)})).filter(x=>x.name&&Number.isFinite(x.top3)).sort((a,b)=>b.top3-a.top3).map((x,i)=>({...x,pRank:i+1}));const m3=new Map((m3State?.rows||[]).map(x=>[String(x.no),Number(x.finishRank)]));const odds={};String(state.odds||'').split(/\r?\n/).forEach(line=>{const m=line.trim().match(/^(\d+)\s+(\d+(?:\.\d+)?)$/);if(m)odds[m[1]]=Number(m[2])});const horses=probs.map(x=>({...x,m3:Number.isFinite(m3.get(x.no))?m3.get(x.no):null,odds:Number.isFinite(odds[x.no])?odds[x.no]:null}));const waveRaw=w.TurbulenceStructureState?.wave;const wave=waveRaw?{supported:!!waveRaw.supported,label:String(waveRaw.label||''),level:String(waveRaw.level||''),score:Number.isFinite(Number(waveRaw.score))?Number(waveRaw.score):null,action:String(waveRaw.action||''),reason:String(waveRaw.reason||'')}:null;const disagreements=localDisagreements(horses);const scenarios=[...d.querySelectorAll('#s4 .sc')].map(sc=>({name:sc.querySelector('.name')?.textContent?.trim()||'',prob:sc.querySelector('.sp')?.textContent?.trim()||'',reason:sc.querySelector('.reason')?.textContent?.trim()||''})).filter(x=>x.name||x.prob);const positions=[...d.querySelectorAll('#positionList .horse')].map(c=>{const t=c.querySelector('.horseName')?.textContent?.trim()||'',m=t.match(/^(\d+)番\s*(.*)$/);return m?{no:m[1],name:m[2].trim(),pos:c.querySelector('.badge')?.textContent?.trim()||'—'}:null}).filter(Boolean);const pace=d.querySelector('#finalDecisionCard .fdRace b')?.textContent?.trim()||d.getElementById('heroSub')?.textContent?.trim()||'';return{build:BUILD,engineBuild:w.RSAAddonHealth?.build||'',m3Build:m3State?.version||'',analyzedAt:Date.now(),title:[state.race.venue,state.race.grade,state.race.raceName].filter(Boolean).join(' '),horses,wave,disagreements,scenarios,positions,pace}}
async function analyze(){if(busy)return;const missing=validate();if(missing.length){showError('入力不足：'+missing.join(' / '));return}if(!window.V4M3Engine?.compute){showError('M3エンジンを読み込めませんでした');return}busy=true;showError('');$('analyzeBtn').disabled=true;$('analyzeBtn').querySelector('span').textContent='解析中…';$('modelStatus').textContent='検証済みエンジン起動中';let engine=null;try{engine=await bootEngine();$('modelStatus').textContent='CSV・市場データ解析中';await feedEngine(engine);try{delete engine.w.CalibratedProbabilityState}catch{engine.w.CalibratedProbabilityState=null}engine.d.getElementById('analyzeBtn')?.click();$('modelStatus').textContent='基礎確率を計算中';try{await waitFor(()=>engine.w.CalibratedProbabilityState?.ready===true,45000,100)}catch(e){throw new Error(`基礎確率を取得できませんでした：${JSON.stringify(engineDiagnostic(engine.w))}`)}const baseHorses=(engine.w.CalibratedProbabilityState?.results||[]).map(x=>({no:String(x.no),name:String(x.name||'')})).filter(x=>x.name);$('modelStatus').textContent='M3末脚を計算中';const m3State=await window.V4M3Engine.compute({blob:state.csv.blob,race:state.race,horses:baseHorses});await Promise.race([waitFor(()=>engine.w.ScenarioStatisticsState?.ready||engine.w.TurbulenceStructureState?.ready,1600,100).catch(()=>null),new Promise(r=>setTimeout(r,1700))]);state.results=extractEngine(engine,m3State);if(!state.results.horses.length)throw new Error(`基礎確率を取得できませんでした：${JSON.stringify(engineDiagnostic(engine.w))}`);state.dirty=false;activeTab='summary';horsePage=0;await saveNow();renderResult();$('modelStatus').textContent='解析完了';$('resultShell').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error(e);showError(e?.message||'解析に失敗しました');$('modelStatus').textContent='解析エラー'}finally{engine?.frame?.remove();busy=false;$('analyzeBtn').disabled=false;$('analyzeBtn').querySelector('span').textContent='解析する'}}
function showError(msg){const box=$('errorBox');if(!msg){box.textContent='';box.classList.add('hidden');return}box.textContent=msg;box.classList.remove('hidden')}
function topMarks(i){return['◎','○','▲'][i]||String(i+1)}
function renderSummary(r){const top=r.horses.slice(0,3);const picks=top.map((h,i)=>`<div class="topPick"><div class="mark">${topMarks(i)}</div><div><div class="horseName">${esc(h.no)}番 ${esc(h.name)}</div><div class="meta">基礎確率 ${h.pRank}位${Number.isFinite(h.m3)?` ｜ M3末脚 ${h.m3}位`:''}${Number.isFinite(h.odds)?` ｜ 単勝 ${h.odds.toFixed(1)}倍`:''}</div></div><div class="prob">${pct(h.top3)}<small>3着内</small></div></div>`).join('');const w=r.wave;const wave=w?`<div class="waveCard"><div><div class="eyebrow">波乱構造</div><b>${esc(w.supported?(w.label||'—'):'未検証')}</b></div><span>${w.score!=null?`構造スコア ${Math.round(w.score*100)}/100<br>`:''}${esc(w.action||w.reason||'')}</span></div>`:'';const split=r.disagreements.filter(x=>Math.abs(x.delta)>=4).slice(0,3);const dis=split.length?`<div class="splitCard"><b>モデル間の食い違い</b><br>${split.map(x=>`${esc(x.no)}番 ${esc(x.name)}：基礎 ${x.pRank}位 / M3 ${Number.isFinite(x.m3Rank)?x.m3Rank+'位':'—'} ｜ ${esc(x.status)}`).join('<br>')}</div>`:'';return `<div class="summaryCard"><div class="eyebrow">最終結論</div><h3>${esc(r.title||'解析結果')}</h3><div class="meta">${esc(r.pace||'展開分析済み')}｜基礎確率を主軸に表示</div>${picks}</div>${wave}${dis}`}
function renderHorses(r){const per=4,total=Math.max(1,Math.ceil(r.horses.length/per));horsePage=Math.min(Math.max(0,horsePage),total-1);const part=r.horses.slice(horsePage*per,(horsePage+1)*per);const cards=part.map(h=>`<div class="horseCard"><div class="horseTop"><div><h3>${esc(h.no)}番 ${esc(h.name)}</h3><div class="meta">基礎確率 ${h.pRank}位${Number.isFinite(h.odds)?` ｜ 単勝 ${h.odds.toFixed(1)}倍`:''}</div></div><span class="pill muted">${Number.isFinite(h.m3)?`M3 ${h.m3}位`:'M3 —'}</span></div><div class="horseGrid"><div class="metric"><small>勝率</small><b>${pct(h.win)}</b></div><div class="metric"><small>3着内</small><b>${pct(h.top3)}</b></div><div class="metric"><small>M3末脚</small><b>${Number.isFinite(h.m3)?h.m3+'位':'—'}</b></div></div></div>`).join('');return `${cards||'<div class="horseCard">全頭データがありません。</div>'}<div class="pager"><button data-prev ${horsePage===0?'disabled':''}>← 前へ</button><span>${horsePage+1} / ${total}</span><button data-next ${horsePage>=total-1?'disabled':''}>次へ →</button></div>`}
function renderScenario(r){if(!r.scenarios.length)return `<div class="scenarioCard"><h3>展開</h3><p>${esc(r.pace||'シナリオデータを取得できませんでした。')}</p></div>`;return r.scenarios.map((s,i)=>`<div class="scenarioCard"><div class="row"><div><div class="eyebrow">${i===0?'SCENARIO':'ALTERNATIVE'}</div><h3>${esc(s.name||'展開')}</h3></div><strong>${esc(s.prob||'')}</strong></div>${s.reason?`<p>${esc(s.reason)}</p>`:''}</div>`).join('')}
function renderPosition(r){if(!r.positions.length)return '<div class="positionCard"><div class="row"><b>位置取りデータなし</b><span>—</span></div></div>';return `<div class="positionCard">${r.positions.map(x=>`<div class="row"><b>${esc(x.no)}番 ${esc(x.name)}</b><span>${esc(x.pos)}</span></div>`).join('')}</div>`}
function renderResult(){const shell=$('resultShell'),r=state.results;if(!r){shell.classList.add('hidden');return}shell.classList.remove('hidden');$('resultTitle').textContent=r.title||'解析結果';$('resultFresh').textContent=state.dirty?'要再解析':'保存済み';$('resultFresh').className=state.dirty?'pill muted':'pill good';[...$('resultTabs').querySelectorAll('[data-tab]')].forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));$('resultPanel').innerHTML=activeTab==='horses'?renderHorses(r):activeTab==='scenario'?renderScenario(r):activeTab==='position'?renderPosition(r):renderSummary(r)}
async function init(){document.documentElement.dataset.rsaV4=BUILD;$('modelStatus').textContent='モデル待機';bindInputs();try{db=await openDb();const saved=await dbGet();hydrate(saved);$('persistStatus').textContent=saved?'前回入力を復元':'端末保存準備済'}catch(e){console.warn('v4 db',e);hydrate(null);$('persistStatus').textContent='簡易保存モード'}applyStateToForm();if(state.results)$('modelStatus').textContent='前回解析を復元';document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')syncFieldBackup()});addEventListener('pagehide',syncFieldBackup)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();