(()=>{'use strict';
const FLOW_KEY='rsa-v4-validated-flow-cache-v2',SC4=['強前傾','前傾','標準','スロー'],$=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),N=v=>Number.isFinite(+v)?+v:null;
let tab='overview',formation='start',lastSig='',timer=null;
function raceKey(){const r=window.V4AppState?.state?.race||{};return[r.raceDate,r.venue,r.raceName,r.surface,r.distance,r.fieldSize,r.grade,r.going].join('|')}
function flow(){try{const x=JSON.parse(localStorage.getItem(FLOW_KEY)||'null');return x?.raceKey===raceKey()?x:null}catch{return null}}
function result(){return window.V4AppState?.state?.results||null}
function pct(v){const n=N(v);return n===null?'—':`${Math.round(n*100)}%`}
function odds(v){const n=N(v);return n===null?'—':`${n.toFixed(1)}倍`}
function scenarioProb(r,F){let p=(F?.fit?.p||F?.scen?.p||[]).map(N);if(p.length===4&&p.every(x=>x!==null)){const z=p.reduce((a,b)=>a+b,0)||1;return p.map(x=>x/z)}p=(r?.rpci?.bands||[]).slice(0,4).map(x=>{const m=String(x.prob||'').match(/([0-9.]+)%/);return m?+m[1]/100:0});return p.length===4?p:[.25,.25,.25,.25]}
function pace3(p){return{H:(p[0]||0)+(p[1]||0),M:p[2]||0,S:p[3]||0}}
function mainPace(p3){return Object.entries(p3).sort((a,b)=>b[1]-a[1])[0]||['M',0]}
function marketScore(r){const w=r?.wave;if(!w?.supported)return null;let s=N(w.score);if(s===null)return null;if(s<=1)s*=100;return Math.max(0,Math.min(100,s))}
function marketLabel(r,s){if(r?.wave?.label)return r.wave.label;if(r?.wave?.action)return r.wave.action;if(s===null)return'判定不足';return s>=67?'波乱寄り':s>=34?'中間':'安定寄り'}
function maps(F){return{q:new Map((F?.q||[]).map(x=>[String(x.no),x])),r:new Map((F?.r||[]).map(x=>[String(x.no),x])),f:new Map((F?.f||[]).map(x=>[String(x.no),x])),fit:new Map((F?.fit?.rows||[]).map(x=>[String(x.no),x]))}}
function marketRanks(hs){const a=hs.filter(h=>N(h.odds)!==null).slice().sort((x,y)=>(+x.odds-+y.odds)||(+x.pRank-+y.pRank));const m=new Map;a.forEach((h,i)=>m.set(String(h.no),i+1));return m}
function laneKey(q){const x=String(q?.lane||'');if(x.includes('内'))return'in';if(x.includes('外'))return'out';return'mid'}
function zone(r){const x=N(r?.pct);if(x===null)return'位置率 —';return x<=.25?'馬群前方25%':x<=.65?'馬群中間':'馬群後方35%'}
function scenarioBandForPace(key,p){if(key==='H')return (p[0]||0)>=(p[1]||0)?0:1;if(key==='M')return 2;return 3}
function classifyBand(r,F,band){const hs=r?.horses||[],m=maps(F),mr=marketRanks(hs),main=[],floats=[],caution=[];for(const h of hs){const f=m.f.get(String(h.no)),pr=N(h.pRank),m3=N(f?.rank??h.m3),sc=N(f?.sc?.[band]?.rank),mk=mr.get(String(h.no))??null;if(pr===null||m3===null||sc===null)continue;const m3Adverse=m3-pr>=4,scAdverse=sc-m3>=4;if(pr<=3){if(!m3Adverse&&!scAdverse)main.push({...h,m3,sc,mk});else caution.push({...h,m3,sc,mk});continue}if(mk!==null&&mk>=4&&m3<=3&&sc<=3)floats.push({...h,m3,sc,mk,strong:pr-m3>=4})}main.sort((a,b)=>a.pRank-b.pRank);floats.sort((a,b)=>(a.m3-b.m3)||(a.sc-b.sc)||(a.mk-b.mk));caution.sort((a,b)=>a.pRank-b.pRank);return{main,floats,caution}}
function titleMeta(){const s=window.V4AppState?.state,r=s?.race||{},res=s?.results;if(!res)return;const t=[r.venue,r.raceName||r.grade].filter(Boolean).join(' '),meta=[r.surface&&r.distance?`${r.surface}${r.distance}m`:null,r.fieldSize?`${r.fieldSize}頭`:null,r.grade,r.going].filter(Boolean).join(' ｜ ');$('v5Title').textContent=t||res.title||'解析結果';$('v5Meta').textContent=meta}
function cardHead(kicker,title,right=''){return `<div class="v5CardHead"><div><small>${E(kicker)}</small><h3>${E(title)}</h3></div>${right?`<span>${E(right)}</span>`:''}</div>`}
function overview(r,F){const p=scenarioProb(r,F),p3=pace3(p),[mp,mpv]=mainPace(p3),score=marketScore(r),label=marketLabel(r,score),exp=N(F?.fit?.exp),leader=Object.entries(p3).sort((a,b)=>b[1]-a[1]),paceWord=mp==='S'?'SLOW':mp==='H'?'HIGH':'MIDDLE',qN=(F?.q||[]).filter(x=>x.v).length,total=(F?.q||[]).length,m3ready=(F?.f||[]).length>0,paceSentence=mp==='H'?'前半負荷が高まりやすく、追走力と持続力の比重が上がる構造。':mp==='S'?'前半が緩みやすく、位置取りと加速局面の比重が上がる構造。':'極端な前傾・スローより標準域が中心。位置と持続のバランスを見るレース。';return `
<div class="v5HeroGrid">
 <section class="v5Card">${cardHead('MARKET STRUCTURE','市場構造','確率ではなく構造スコア')}
  <div class="v5Gauge"><div><div class="v5GaugeRing" style="--v:${score??0}"><div class="v5GaugeValue"><strong>${score===null?'—':Math.round(score)}</strong><small>STRUCTURE SCORE</small></div></div><div class="v5GaugeCaption">${E(label)}</div></div></div>
  <div class="v5MetricChips"><span class="v5Chip">波乱構造モデル</span><span class="v5Chip">勝率補正には未使用</span></div>
 </section>
 <section class="v5Card">${cardHead('PACE PROJECTION','想定ペース',`主想定 ${paceWord}`)}
  <div class="v5PaceBars">${leader.map(([k,v])=>`<div class="v5PaceRow"><b>${k}</b><div class="v5PaceTrack"><div class="v5PaceFill" style="width:${Math.round(v*100)}%"></div></div><strong>${Math.round(v*100)}%</strong></div>`).join('')}</div>
  <div class="v5PacePrimary"><small>PRIMARY SCENARIO</small><b>${paceWord} ${Math.round(mpv*100)}%</b></div>
 </section>
</div>
<section class="v5Card">${cardHead('RPCI','ペース構造',exp!==null?`期待RPCI ${exp.toFixed(1)}`:'4帯確率')}
 <div class="v5RpciStrip">${p.map((v,i)=>`<div class="v5RpciBand ${v===Math.max(...p)?'active':''}"><small>${E(SC4[i])}</small><b>${Math.round(v*100)}%</b></div>`).join('')}</div>
 <div class="v5MetricChips"><span class="v5Chip">H = 強前傾 + 前傾</span><span class="v5Chip">M = 標準</span><span class="v5Chip">S = スロー</span></div>
</section>
<section class="v5Card">${cardHead('RACE OUTLOOK','レース構造要約')}
 <div class="v5Outlook"><strong>主想定は ${paceWord} ${Math.round(mpv*100)}%。</strong><br>${E(paceSentence)}<br>位置予測 ${qN}/${total||'—'}頭、残600m→M3 ${m3ready?'計算済み':'準備中'}。各モデルは足し算せず、シナリオ間の一致・不一致で読みます。</div>
 <div class="v5MetricChips"><span class="v5Chip good">位置 OOS検証済み</span><span class="v5Chip good">M3 OOS検証済み</span><span class="v5Chip warn">内外は参考推定</span></div>
</section>`}
function startFormation(r,F){const m=maps(F),hs=(r?.horses||[]).map(h=>({h,q:m.q.get(String(h.no))})).filter(x=>x.q?.v&&N(x.q.pos)!==null),n=Math.max(1,...hs.map(x=>N(x.q.pos)||1)),lanes={in:[],mid:[],out:[]};hs.forEach(x=>lanes[laneKey(x.q)].push(x));const lane=(key,title)=>`<div class="v5Lane"><div class="v5LaneTitle">${title}</div>${lanes[key].map(({h,q})=>{const top=26+((N(q.pos)-1)/(Math.max(2,n)-1))*270;return `<div class="v5HorseDot" style="top:${top}px" title="${E(h.name)}"><span>${E(h.no)}</span><small>${N(q.pos).toFixed(1)}</small></div>`}).join('')}</div>`;return `${cardHead('FORMATION','ゲート → 1角','縦=前後 / 横=内外参考')}<div class="v5TrackShell"><div class="v5TrackLabels"><span>FRONT / 1角へ</span><span>BACK</span></div><div class="v5TrackGrid">${lane('in','内')}${lane('mid','中')}${lane('out','外')}</div></div><div class="v5MetricChips"><span class="v5Chip good">縦位置：検証済み1角予測</span><span class="v5Chip warn">内外：参考推定・順位未使用</span></div>`}
function sixFormation(r,F,key){const p=scenarioProb(r,F),band=scenarioBandForPace(key,p),m=maps(F),rows=(r?.horses||[]).map(h=>({h,rr:m.r.get(String(h.no)),f:m.f.get(String(h.no))})).filter(x=>N(x.rr?.pred)!==null||N(x.f?.gap)!==null).sort((a,b)=>(N(a.rr?.pred)??N(a.f?.gap)??99)-(N(b.rr?.pred)??N(b.f?.gap)??99));return `${cardHead('LAST 600M → GOAL',`残600m → GOAL / ${key}ペース`,`${SC4[band]}代表`)}<div class="v5QueueList">${rows.map(({h,rr,f},i)=>{const gap=N(rr?.pred)??N(f?.gap),sc=N(f?.sc?.[band]?.rank),move=sc===null?null:(i+1)-sc,mt=move===null?'—':move>0?`↑${move}`:move<0?`↓${Math.abs(move)}`:'→';return `<div class="v5QueueRow"><div class="v5No">${E(h.no)}</div><div class="v5QueueMain"><b>${E(h.name)}</b><span>残600m ${gap===null?'—':`+${gap.toFixed(1)}秒`} ｜ ${E(zone(rr))}</span></div><div class="v5Move"><strong>${mt}</strong><small>${sc===null?'GOAL —':`GOAL ${sc}位`}</small></div></div>`}).join('')}</div><div class="v5MetricChips"><span class="v5Chip">残600m位置は共通予測</span><span class="v5Chip">GOAL順位だけシナリオ別</span></div>`}
function formationView(r,F){return `<section class="v5Card"><div class="v5Segmented"><button data-form="start" class="${formation==='start'?'active':''}">START → 1角</button><button data-form="S" class="${formation==='S'?'active':''}">残600m S</button><button data-form="M" class="${formation==='M'?'active':''}">残600m M</button><button data-form="H" class="${formation==='H'?'active':''}">残600m H</button></div>${formation==='start'?startFormation(r,F):sixFormation(r,F,formation)}</section>`}
function miniHorse(x,kind){const mark=kind==='float'?(x.strong?'↗':'↑'):kind==='caution'?'△':'◎';return `<div class="v5MiniHorse"><b>${mark} ${E(x.no)} ${E(x.name)}</b><span>M3 ${x.m3}位 / SC ${x.sc}位</span></div>`}
function scenarioView(r,F){const p=scenarioProb(r,F),p3=pace3(p),order=['S','M','H'].sort((a,b)=>p3[b]-p3[a]);return `<div class="v5ScenarioGrid">${order.map(key=>{const band=scenarioBandForPace(key,p),c=classifyBand(r,F,band),word=key==='S'?'SLOW':key==='M'?'MIDDLE':'HIGH';return `<section class="v5ScenarioCard"><div class="v5ScenarioTop"><div><div class="v5Eyebrow">${word} SCENARIO</div><b>${E(SC4[band])}代表</b></div><strong>${Math.round(p3[key]*100)}%</strong></div><div class="v5ScenarioCols"><div class="v5ScenarioBox"><small>本線候補</small>${c.main.length?c.main.map(x=>miniHorse(x,'main')).join(''):'<div class="v5MiniHorse"><span>該当なし</span></div>'}</div><div class="v5ScenarioBox"><small>構造浮上馬</small>${c.floats.length?c.floats.map(x=>miniHorse(x,'float')).join(''):'<div class="v5MiniHorse"><span>該当なし</span></div>'}</div></div>${c.caution.length?`<div class="v5MetricChips"><span class="v5Chip warn">要注意人気馬 ${c.caution.map(x=>x.no).join('・')}</span></div>`:''}</section>`}).join('')}<section class="v5Card"><div class="v5Outlook">構造浮上は <strong>単勝順4位以下 ∩ M3 Top3 ∩ 当該シナリオTop3</strong>。総合点や恣意的な重み付けは作っていません。HはRPCIの「強前傾・前傾」のうち確率が高い帯を代表として表示します。</div></section></div>`}
function horseSummary(h,q,rr,f,fit,mr){const tags=[];if(q?.v&&N(q.pos)!==null)tags.push(`1角 ${N(q.pos).toFixed(1)}番手`);if(fit?.label)tags.push(`RPCI ${fit.label}`);if(f?.beta?.length)tags.push(...f.beta.slice(0,2).map(x=>x.t));const m3=N(f?.rank??h.m3),base=N(h.pRank),delta=base!==null&&m3!==null?base-m3:null,lead=delta!==null&&delta>=4?'市場よりM3が大きく上位。':delta!==null&&delta<=-4?'市場基礎よりM3が大きく下位。':'市場基礎とM3に大幅な乖離なし。';return `${lead}${tags.length?' '+tags.join(' / ')+'。':''}${mr>=4&&m3!==null&&m3<=3?' 構造浮上候補を確認。':''}`}
function horsesView(r,F){const m=maps(F),mr=marketRanks(r?.horses||[]),p=scenarioProb(r,F);return `<div class="v5HorseCards">${(r?.horses||[]).map(h=>{const no=String(h.no),q=m.q.get(no),rr=m.r.get(no),f=m.f.get(no),fit=m.fit.get(no),rank=mr.get(no)||null,sc=(f?.sc||[]).map((x,i)=>({n:SC4[i],r:N(x.rank),p:p[i]})).filter(x=>x.r!==null).sort((a,b)=>b.p-a.p),best=sc.slice().sort((a,b)=>a.r-b.r)[0];return `<section class="v5HorseCard"><div class="v5HorseTop"><div class="v5No">${E(no)}</div><div class="v5HorseName"><b>${E(h.name)}</b><small>基礎 ${h.pRank??'—'}位 ｜ M3 ${N(f?.rank??h.m3)??'—'}位 ｜ 単勝順 ${rank??'—'}位</small></div><div class="v5HorseOdds"><b>${odds(h.odds)}</b><small>3着内基礎 ${pct(h.top3)}</small></div></div><div class="v5FeatureGrid"><div class="v5Feature"><small>1角</small><b>${q?.v&&N(q.pos)!==null?`${N(q.pos).toFixed(1)}番手`:'履歴不足'}</b></div><div class="v5Feature"><small>残600m</small><b>${N(rr?.pred)!==null?`+${N(rr.pred).toFixed(1)}秒`:N(f?.gap)!==null?`+${N(f.gap).toFixed(1)}秒`:'—'}</b></div><div class="v5Feature"><small>ペース適性</small><b>${E(fit?.label||'—')}</b></div><div class="v5Feature"><small>得意SC</small><b>${best?`${E(best.n)} ${best.r}位`:'—'}</b></div><div class="v5Feature"><small>データ</small><b>${q?.n?`${q.n}走`:'—'}</b></div><div class="v5Feature"><small>内外</small><b>${E(q?.lane||'参考なし')}</b></div></div><div class="v5MetricChips">${(f?.beta||[]).slice(0,4).map(x=>`<span class="v5Chip">${E(x.t)} β</span>`).join('')}</div><div class="v5HorseSummary">${E(horseSummary(h,q,rr,f,fit,rank))}</div></section>`}).join('')}</div>`}
function render(){const r=result(),F=flow();if(!r)return;titleMeta();$('v5ResultShell').classList.remove('hidden');$('v5Tabs').classList.remove('hidden');const p=$('v5Panel');if(!F){p.innerHTML=`<section class="v5Card">${cardHead('ANALYSIS','検証済みフローを同期中')}<div class="v5Outlook">位置・残600m・RPCI・M3の表示データを準備しています。</div></section>`;return}if(tab==='overview')p.innerHTML=overview(r,F);else if(tab==='formation')p.innerHTML=formationView(r,F);else if(tab==='scenario')p.innerHTML=scenarioView(r,F);else p.innerHTML=horsesView(r,F);document.querySelectorAll('#v5Tabs [data-v5-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v5Tab===tab));}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{const r=result(),F=flow(),sig=r?`${r.analyzedAt}|${F?.capturedAt||0}|${tab}|${formation}|${window.V4CandidateState?.build||''}`:'';if(sig&&sig!==lastSig){lastSig=sig;render()}},100)}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-v5-tab]');if(t){tab=t.dataset.v5Tab;lastSig='';render();return}const f=e.target.closest('[data-form]');if(f){formation=f.dataset.form;lastSig='';render();return}if(e.target.closest('#analyzeBtn')){setTimeout(schedule,250)}});setInterval(()=>{const r=result();if(r){const F=flow(),sig=`${r.analyzedAt}|${F?.capturedAt||0}|${tab}|${formation}|${window.V4CandidateState?.build||''}`;if(sig!==lastSig){lastSig=sig;render()}}},500)}
function init(){bind();schedule()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();